"""Sprint 6h₂ · Phase 4.9 closure pin (ADR-0071 / ADR-0072).

Pi parity invariant: every Pi-verified surface in the Phase 4.9 scope
(9 RPC commands wired through the harness) has a corresponding binding
in Aelix. After Sprint 6h₂ the dispatcher matches Pi on **22 of 29**
commands; the remaining 7 (5 session-tree + 2 session-inspection) are
owned by ADR-0072 and defer to Sprint 6h₃.

Closure date: **2026-05-20**. Pi SHA pinned by ADR-0034:
``734e08edf82ff315bc3d96472a6ebfa69a1d8016``.

Roster: P-245 ~ P-253.
"""

from __future__ import annotations

import json
from collections.abc import AsyncIterator
from pathlib import Path
from typing import Any

import pytest
from aelix_agent_core.harness.core import AgentHarness, AgentHarnessOptions
from aelix_ai.messages import AssistantMessage, TextContent
from aelix_ai.streaming import (
    AssistantEndEvent,
    AssistantMessageEvent,
    AssistantStartEvent,
    Context,
    Model,
    SimpleStreamOptions,
)
from aelix_coding_agent.rpc.rpc_mode import (
    DEFERRED_COMMANDS,
    SUPPORTED_COMMANDS,
    _handle_get_state,
    build_dispatch_table,
)
from aelix_coding_agent.rpc.rpc_types import (
    RpcCommandCycleThinkingLevel,
    RpcCommandGetState,
    RpcSuccessResponse,
)

_FIXTURES = Path(__file__).parent / "fixtures"


def _load_fixture() -> dict:
    return json.loads((_FIXTURES / "pi_rpc_9_commands_734e08e.json").read_text())


def _stream() -> Any:
    async def fn(
        model: Model,
        context: Context,
        options: SimpleStreamOptions,
    ) -> AsyncIterator[AssistantMessageEvent]:
        yield AssistantStartEvent(partial=AssistantMessage(content=[]))
        yield AssistantEndEvent(
            message=AssistantMessage(
                content=[TextContent(text="ok")],
                stop_reason="end_turn",
            )
        )

    return fn


# === §A — Counts: 22 supported / 7 deferred / 29 total =======================


def test_supported_count_is_22_after_sprint_6h2() -> None:
    """Sprint 6h₁ left 13 supported; Sprint 6h₂ adds 9 → 22.

    Sprint 6h₃ (ADR-0073 / P-268~P-274) wires 2 more → 24 supported.
    Sprint 6h₄a (ADR-0075 / P-293~P-298) wires 2 more → 26 supported.
    Closure pin retains the original name; the body asserts the
    live count.
    """

    assert len(SUPPORTED_COMMANDS) == 26


def test_deferred_count_is_7_after_sprint_6h2() -> None:
    """Sprint 6h₁ left 16 deferred; Sprint 6h₂ drops 9 → 7.

    Sprint 6h₃ (ADR-0073 / P-268~P-274) drops 2 more → 5 deferred.
    Sprint 6h₄a (ADR-0075 / P-293~P-298) drops 2 more → 3 deferred.
    """

    assert len(DEFERRED_COMMANDS) == 3


def test_supported_plus_deferred_is_29() -> None:
    """Pi parity invariant: union covers the full Pi command set."""

    assert SUPPORTED_COMMANDS.isdisjoint(DEFERRED_COMMANDS)
    assert len(SUPPORTED_COMMANDS) + len(DEFERRED_COMMANDS) == 29


# === §B — 9 new commands wired ===============================================


_NEW_COMMANDS = {
    "steer",
    "follow_up",
    "cycle_thinking_level",
    "set_steering_mode",
    "set_follow_up_mode",
    "set_auto_compaction",
    "set_auto_retry",
    "abort_retry",
    "abort_bash",
}


def test_all_nine_new_commands_in_supported() -> None:
    for cmd in _NEW_COMMANDS:
        assert cmd in SUPPORTED_COMMANDS, f"{cmd!r} missing from SUPPORTED"


def test_all_nine_new_commands_removed_from_deferred() -> None:
    for cmd in _NEW_COMMANDS:
        assert cmd not in DEFERRED_COMMANDS, f"{cmd!r} still in DEFERRED"


def test_dispatcher_table_routes_all_nine() -> None:
    """Every newly wired command resolves to a real (non-stub) handler."""

    table = build_dispatch_table()
    for cmd in _NEW_COMMANDS:
        handler = table.get(cmd)
        assert handler is not None, f"No dispatcher entry for {cmd!r}"
        # Handler name must NOT contain ``deferred`` (stubs are
        # generated by ``_make_deferred_handler``).
        name = getattr(handler, "__qualname__", repr(handler))
        assert "deferred" not in name.lower()


# === §C — Carry-forward 7 deferred all map to ADR-0072 =======================


def test_remaining_seven_deferred_are_session_tree_or_inspection() -> None:
    """Sprint 6h₂ left 7 deferred (2 session-inspection + 5 session-tree).
    Sprint 6h₃ (ADR-0073) wires the 2 session-inspection commands so the
    remaining set narrows to the 5 session-tree commands deferred to
    Sprint 6h₄ per ADR-0074.
    Sprint 6h₄a (ADR-0075) wires the 2 read-only navigation commands
    (``get_fork_messages`` + ``get_last_assistant_text``); the
    remaining set narrows to the 3 session-tree commands deferred to
    Sprint 6h₄b per ADR-0076.
    """

    expected = {"switch_session", "fork", "clone"}
    assert set(DEFERRED_COMMANDS) == expected


def test_remaining_seven_deferred_own_adr_0072() -> None:
    """Sprint 6h₂ closure pin restated owners to ADR-0072. Sprint 6h₃
    (ADR-0073) wires the 2 session-inspection commands; the remaining
    5 session-tree commands are restated to ADR-0074.
    Sprint 6h₄a (ADR-0075) wires the 2 read-only navigation commands;
    the remaining 3 session-tree commands are restated to ADR-0076.
    Sprint 6h₄b (ADR-0078) rebrands the same 3 session-tree owners
    ADR-0076 → ADR-0078 per spec §D.5 (foundation lands; 6h₄c wires
    the handlers). Accept any of the four prefixes so the closure
    pin survives the cascading transitions.
    """

    for cmd, owner in DEFERRED_COMMANDS.items():
        assert (
            "ADR-0072" in owner
            or "ADR-0074" in owner
            or "ADR-0076" in owner
            or "ADR-0078" in owner
        ), (
            f"{cmd!r} owner string {owner!r} does not cite "
            f"ADR-0072 / ADR-0074 / ADR-0076 / ADR-0078"
        )


# === §D — cycle_thinking_level algorithm matches Pi fixture ==================


async def test_cycle_thinking_level_returns_none_for_non_reasoning_model() -> None:
    """Fixture algorithm step 2: ``len(levels) <= 1 → null``."""

    h = AgentHarness(
        AgentHarnessOptions(
            model=Model(id="m", provider="p", reasoning=False),
            stream_fn=_stream(),
        )
    )
    try:
        result = await h.cycle_thinking_level()
        assert result is None
    finally:
        await h.dispose()


async def test_cycle_thinking_level_rotates_and_persists() -> None:
    """Fixture algorithm steps 3-6: rotate, persist, return."""

    h = AgentHarness(
        AgentHarnessOptions(
            model=Model(
                id="m",
                provider="p",
                reasoning=True,
                thinking_level_map={
                    "off": "off",
                    "minimal": "minimal",
                    "low": "low",
                    "medium": "medium",
                    "high": "high",
                    "xhigh": "xhigh",
                },
            ),
            thinking_level="off",
            stream_fn=_stream(),
        )
    )
    try:
        new_level = await h.cycle_thinking_level()
        # Pi forward rotation: off → minimal.
        assert new_level == "minimal"
        assert h.state.thinking_level == "minimal"
    finally:
        await h.dispose()


# === §E — Mode setter validation (Pi TS narrow → Aelix runtime check) ========


async def test_set_steering_mode_invalid_raises_value_error() -> None:
    """Pi narrows mode at compile time; Aelix runtime-checks → ValueError."""

    h = AgentHarness(AgentHarnessOptions(stream_fn=_stream()))
    try:
        with pytest.raises(ValueError):
            h.set_steering_mode("invalid")
    finally:
        await h.dispose()


async def test_set_follow_up_mode_invalid_raises_value_error() -> None:
    h = AgentHarness(AgentHarnessOptions(stream_fn=_stream()))
    try:
        with pytest.raises(ValueError):
            h.set_follow_up_mode("invalid")
    finally:
        await h.dispose()


# === §F — Cycle thinking level RPC response shape (Pi: ``{level} | null``) ===


async def test_rpc_cycle_thinking_level_null_data_shape() -> None:
    from aelix_coding_agent.rpc.rpc_mode import _handle_cycle_thinking_level

    h = AgentHarness(
        AgentHarnessOptions(
            model=Model(id="m", provider="p", reasoning=False),
            stream_fn=_stream(),
        )
    )
    try:
        cmd = RpcCommandCycleThinkingLevel(id="r1")
        response = await _handle_cycle_thinking_level(h, cmd)
        assert isinstance(response, RpcSuccessResponse)
        assert response.command == "cycle_thinking_level"
        assert response.data is None
    finally:
        await h.dispose()


async def test_rpc_cycle_thinking_level_level_dict_shape() -> None:
    from aelix_coding_agent.rpc.rpc_mode import _handle_cycle_thinking_level

    h = AgentHarness(
        AgentHarnessOptions(
            model=Model(
                id="m",
                provider="p",
                reasoning=True,
                thinking_level_map={
                    "off": "off",
                    "minimal": None,
                    "low": None,
                    "medium": None,
                    "high": "high",
                },
            ),
            thinking_level="off",
            stream_fn=_stream(),
        )
    )
    try:
        cmd = RpcCommandCycleThinkingLevel(id="r2")
        response = await _handle_cycle_thinking_level(h, cmd)
        assert isinstance(response, RpcSuccessResponse)
        # Supported levels collapse to ["off", "high"]; rotating from
        # "off" jumps directly to "high".
        assert response.data == {"level": "high"}
    finally:
        await h.dispose()


# === §G — `_handle_get_state` real auto_compaction_enabled source (P-252) ====


async def test_get_state_reflects_real_auto_compaction_enabled() -> None:
    """P-252: ``_handle_get_state`` reads ``harness.auto_compaction_enabled``
    instead of the Sprint 6d hardcoded ``True``.
    """

    h = AgentHarness(AgentHarnessOptions(stream_fn=_stream()))
    try:
        # Default is True (matches Pi fixture).
        cmd = RpcCommandGetState(id="r1")
        response = await _handle_get_state(h, cmd)
        assert isinstance(response, RpcSuccessResponse)
        assert isinstance(response.data, dict)
        assert response.data["autoCompactionEnabled"] is True

        # Flip the harness flag — the next ``get_state`` must reflect False.
        h.set_auto_compaction_enabled(False)
        response = await _handle_get_state(h, RpcCommandGetState(id="r2"))
        assert isinstance(response, RpcSuccessResponse)
        assert isinstance(response.data, dict)
        assert response.data["autoCompactionEnabled"] is False
    finally:
        await h.dispose()


# === §H — Pi fixture immutability ============================================


def test_pi_sha_pinned_to_phase_4_9_baseline() -> None:
    fixture = _load_fixture()
    assert fixture["pi_sha"] == "734e08edf82ff315bc3d96472a6ebfa69a1d8016"


def test_fixture_command_arithmetic_matches_implementation() -> None:
    """Fixture's ``after_sprint_6h_2`` describes 22 / 7 / 29 — the same
    numbers asserted by §A above.
    """

    fixture = _load_fixture()
    arithmetic = fixture["command_count_arithmetic"]
    assert arithmetic["after_sprint_6h_2"] == "22 supported / 7 deferred / 29 total"
    assert set(arithmetic["supported_added"]) == _NEW_COMMANDS


# === §I — Sprint 6h₂ W6 regression pins =====================================


def test_fixture_line_numbers_match_pi_at_sha_734e08e() -> None:
    """Sprint 6h₂ W6 (P-258 BLOCKING): the W5 audit confirmed the 9 case
    sites in ``rpc-mode.ts`` live at lines 483-547 (NOT 528-635 as the
    W1 draft suggested). The W0 fixture must cite the audited line
    numbers so future audits resolve cleanly against the pinned SHA.
    """

    fixture = _load_fixture()
    handlers = fixture["pi_handlers"]
    # Spot-check the 4 most-cited handlers (steer + cycle + auto +
    # abort_bash). Each ``lines`` field must fall in 483-547.
    expected_lines = {
        "steer": "483-486",
        "follow_up": "488-491",
        "cycle_thinking_level": "486-490",
        "set_steering_mode": "498-501",
        "set_follow_up_mode": "503-506",
        "set_auto_compaction": "516-519",
        "set_auto_retry": "525-528",
        "abort_retry": "530-533",
        "abort_bash": "544-547",
    }
    for cmd, expected in expected_lines.items():
        assert handlers[cmd]["lines"] == expected, (
            f"{cmd!r} fixture line range {handlers[cmd]['lines']!r} "
            f"does not match the W5-audited {expected!r}"
        )


async def test_cycle_thinking_level_non_reasoning_supportsThinking_guard() -> None:
    """Sprint 6h₂ W6 (P-254 BLOCKING): the Pi
    ``agent-session.ts:1539`` short-circuit fires on
    ``!supportsThinking()`` (``!!this.model?.reasoning``). A non-
    reasoning model whose ``thinking_level_map`` *could* yield more
    than one level (defensive) must still return :data:`None` because
    ``reasoning`` is False.
    """

    h = AgentHarness(
        AgentHarnessOptions(
            model=Model(
                id="m",
                provider="p",
                reasoning=False,
                # Non-reasoning model would normally collapse levels
                # to ["off"]; even if the map said otherwise, the
                # supportsThinking guard pre-empts.
                thinking_level_map={"off": "off", "high": "high"},
            ),
            stream_fn=_stream(),
        )
    )
    try:
        result = await h.cycle_thinking_level()
        assert result is None
    finally:
        await h.dispose()


async def test_cycle_thinking_level_reasoning_model_single_level_wraps() -> None:
    """Sprint 6h₂ W6 (P-254 BLOCKING): a reasoning-capable model with
    a degenerate ``thinking_level_map`` whose only non-null entry is
    ``"off"`` collapses ``levels`` to ``["off"]``. Pi rotates via
    ``(0+1)%1 == 0`` and returns ``"off"``; the prior Aelix
    ``len(levels) <= 1`` guard silently returned :data:`None`.
    """

    h = AgentHarness(
        AgentHarnessOptions(
            model=Model(
                id="m",
                provider="p",
                reasoning=True,
                thinking_level_map={
                    "off": "off",
                    "minimal": None,
                    "low": None,
                    "medium": None,
                    "high": None,
                },
            ),
            thinking_level="off",
            stream_fn=_stream(),
        )
    )
    try:
        result = await h.cycle_thinking_level()
        assert result == "off"
        assert h.state.thinking_level == "off"
    finally:
        await h.dispose()


def test_message_queue_set_mode_rejects_invalid() -> None:
    """Sprint 6h₂ W6 (P-265 BLOCKING): the ``_MessageQueue.set_mode``
    helper rejects mode strings that don't satisfy the Pi narrow.
    """

    from aelix_agent_core.harness.core import _MessageQueue

    queue: _MessageQueue = _MessageQueue("all")
    with pytest.raises(ValueError, match="queue mode must be 'all' or 'one-at-a-time'"):
        queue.set_mode("invalid")  # type: ignore[arg-type]


async def test_steer_keyword_only_images_marker() -> None:
    """Sprint 6h₂ W6 (P-263 MAJOR): ``images`` is keyword-only on
    :meth:`AgentHarness.steer` / :meth:`AgentHarness.follow_up`.
    """

    import inspect

    sig_steer = inspect.signature(AgentHarness.steer)
    images_param = sig_steer.parameters["images"]
    assert images_param.kind is inspect.Parameter.KEYWORD_ONLY

    sig_follow_up = inspect.signature(AgentHarness.follow_up)
    images_param = sig_follow_up.parameters["images"]
    assert images_param.kind is inspect.Parameter.KEYWORD_ONLY


def test_decode_images_strict_camel_case_only() -> None:
    """Sprint 6h₂ W6 (P-262 BLOCKING): the decoder is strict-camelCase
    only. Pi sends ``ImageContent.mimeType`` (TS narrow); a snake_case
    payload or missing field raises :exc:`ValueError`.
    """

    from aelix_coding_agent.rpc.rpc_mode import _decode_images

    # Pi wire shape: passes.
    decoded = _decode_images(
        [{"mimeType": "image/png", "data": "AAA"}]
    )
    assert decoded is not None
    assert decoded[0].mime_type == "image/png"
    assert decoded[0].data == "AAA"

    # snake_case → ValueError.
    with pytest.raises(ValueError, match="missing required 'mimeType'"):
        _decode_images([{"mime_type": "image/png", "data": "AAA"}])

    # Non-dict entry → ValueError.
    with pytest.raises(ValueError, match="must be a dict"):
        _decode_images(["not-a-dict"])  # type: ignore[list-item]


def test_decode_images_none_and_empty_short_circuit() -> None:
    """Sprint 6h₂ (P-251): :data:`None` and empty list both short-
    circuit to :data:`None` so the harness falls through to text-only.
    """

    from aelix_coding_agent.rpc.rpc_mode import _decode_images

    assert _decode_images(None) is None
    assert _decode_images([]) is None


async def test_get_state_reflects_real_auto_retry_enabled() -> None:
    """Sprint 6h₂ W6 (P-264 BLOCKING): ``_handle_get_state`` populates
    the new ``autoRetryEnabled`` wire field from
    :attr:`AgentHarness.auto_retry_enabled`.
    """

    h = AgentHarness(AgentHarnessOptions(stream_fn=_stream()))
    try:
        # Default is True (matches Pi ``agent-session.ts:2536-2538``).
        cmd = RpcCommandGetState(id="r1")
        response = await _handle_get_state(h, cmd)
        assert isinstance(response, RpcSuccessResponse)
        assert isinstance(response.data, dict)
        assert response.data["autoRetryEnabled"] is True

        h.set_auto_retry_enabled(False)
        response = await _handle_get_state(h, RpcCommandGetState(id="r2"))
        assert isinstance(response, RpcSuccessResponse)
        assert isinstance(response.data, dict)
        assert response.data["autoRetryEnabled"] is False
    finally:
        await h.dispose()


async def test_auto_retry_enabled_public_property_exists() -> None:
    """Sprint 6h₂ W6 (P-264 BLOCKING): ``AgentHarness.auto_retry_enabled``
    public property is sibling-symmetric with
    ``auto_compaction_enabled``.
    """

    h = AgentHarness(AgentHarnessOptions(stream_fn=_stream()))
    try:
        assert h.auto_retry_enabled is True
        h.set_auto_retry_enabled(False)
        assert h.auto_retry_enabled is False
    finally:
        await h.dispose()


async def test_set_steering_mode_invalid_surfaces_rpc_error() -> None:
    """Sprint 6h₂ W6 (P-261): runtime validation on the harness setter
    propagates through the RPC handler as a Pi-shape
    :class:`RpcErrorResponse` (success: False).
    """

    from aelix_coding_agent.rpc.rpc_mode import _handle_set_steering_mode
    from aelix_coding_agent.rpc.rpc_types import (
        RpcCommandSetSteeringMode,
        RpcErrorResponse,
    )

    h = AgentHarness(AgentHarnessOptions(stream_fn=_stream()))
    try:
        cmd = RpcCommandSetSteeringMode(mode="invalid", id="r1")  # type: ignore[arg-type]
        response = await _handle_set_steering_mode(h, cmd)
        assert isinstance(response, RpcErrorResponse)
        assert response.command == "set_steering_mode"
        assert "all" in response.error
    finally:
        await h.dispose()


def test_session_state_wire_shape_has_auto_retry_enabled() -> None:
    """Sprint 6h₂ W6 (P-264 BLOCKING): ``RpcSessionState.to_json``
    surfaces ``autoRetryEnabled`` on the wire.
    """

    from aelix_coding_agent.rpc.rpc_types import RpcSessionState

    wire = RpcSessionState().to_json()
    assert "autoRetryEnabled" in wire
    assert wire["autoRetryEnabled"] is True

    state = RpcSessionState(auto_retry_enabled=False)
    assert state.to_json()["autoRetryEnabled"] is False
