"""Aelix AI primitives — messages, tools, streaming.

Mirrors the pi-ai package shape so the agent loop stays provider-agnostic and
tests can supply a mock ``stream_fn`` (Phase 1.1) before real provider adapters
land in Phase 2 under ``aelix_ai.providers``.
"""

from aelix_ai.api_registry import (
    clear_providers,
    get_registered_providers,
    register_provider,
    register_provider_object,
    unregister_provider,
    unregister_providers_by_source,
)
from aelix_ai.messages import (
    AssistantMessage,
    ContentBlock,
    ImageContent,
    Message,
    TextContent,
    ToolCallContent,
    ToolResultMessage,
    UserMessage,
)
from aelix_ai.streaming import (
    AssistantDoneEvent,
    AssistantEndEvent,
    AssistantErrorEvent,
    AssistantMessageEvent,
    AssistantStartEvent,
    Context,
    Cost,
    Model,
    ProviderResponse,
    SimpleStreamOptions,
    StreamFn,
    StreamSimpleError,
    TextDeltaEvent,
    TextEndEvent,
    TextStartEvent,
    ThinkingDeltaEvent,
    ThinkingEndEvent,
    ThinkingStartEvent,
    ToolCallDeltaEvent,
    ToolCallEndEvent,
    ToolCallStartEvent,
    stream_simple,
)
from aelix_ai.tools import (
    Tool,
    ToolContent,
    ToolExecute,
    ToolExecutionContext,
    ToolPartialCallback,
    ToolResult,
    validate_tool_arguments,
)

__all__ = [
    "AssistantDoneEvent",
    "AssistantEndEvent",
    "AssistantErrorEvent",
    "AssistantMessage",
    "AssistantMessageEvent",
    "AssistantStartEvent",
    "ContentBlock",
    "Context",
    "Cost",
    "ImageContent",
    "Message",
    "Model",
    "ProviderResponse",
    "SimpleStreamOptions",
    "StreamFn",
    "StreamSimpleError",
    "TextContent",
    "TextDeltaEvent",
    "TextEndEvent",
    "TextStartEvent",
    "ThinkingDeltaEvent",
    "ThinkingEndEvent",
    "ThinkingStartEvent",
    "Tool",
    "ToolCallContent",
    "ToolCallDeltaEvent",
    "ToolCallEndEvent",
    "ToolCallStartEvent",
    "ToolContent",
    "ToolExecute",
    "ToolExecutionContext",
    "ToolPartialCallback",
    "ToolResult",
    "ToolResultMessage",
    "UserMessage",
    "clear_providers",
    "get_registered_providers",
    "register_provider",
    "register_provider_object",
    "stream_simple",
    "unregister_provider",
    "unregister_providers_by_source",
    "validate_tool_arguments",
]
