"""Aelix terminal logo — the startup banner art.

GENERATED by ``scripts/generate_logo_art.py`` from ``docs/assets/brand/*.svg``;
edit the brand SVGs and re-run that script rather than editing this file. The
art is embedded as plain string constants — not a packaged data file — so it
lands in the built wheel with no ``package-data`` / ``MANIFEST.in`` config and
no runtime dependency: printing the banner is printing a string.

The glyphs are quadrant block elements (U+2596..U+259F and friends), which are
Unicode 1.1 and therefore drawn by every terminal — unlike the finer sextant
and octant mosaics, which several major terminals render as tofu. Each cell
carries one foreground colour and no background paint, so a terminal that
strips colour still shows the exact silhouette. The TUI renders this through
``Text.from_ansi``, which degrades cleanly on no-color terminals.
"""

from __future__ import annotations

# The compact lockup: the Forged Planes mark beside the Aelix wordmark.
_LOGO_LINES = (
    "    \u259d\u2588\u2588\u2588\u2588\u2596  \u259f\u2588\u2588\u2588\u259b",
    "     \u259d\u259c\u2588\u2588\u2588\u2584\u259f\u2588\u2588\u2588\u2580",
    "       \u259c\u2588\u2588\u2588\u2588\u2588\u2588\u2598                               \u2588\u2588",
    "        \u259c\u2588\u2588\u2588\u2588\u2598            \u2588\u2588\u2588           \u2590\u2588\u2588\u258c  \u2588\u2588",
    "       \u259f\u2588\u2588\u2588\u2588\u2588\u2588\u2596          \u2590\u2588\u2588\u2588\u258c   \u2597\u2584\u2584\u2584\u2584\u2584 \u2590\u2588\u2588\u258c \u2597\u2584\u2584\u2596\u2584\u2584\u2584 \u2597\u2584\u2584",
    "      \u259f\u2588\u2588\u2588\u259b\u2588\u2588\u2588\u2588\u2596         \u2588\u2588\u2588\u2588\u2588   \u2588\u2588\u2580\u2580\u259c\u2588\u258c\u2590\u2588\u2588\u258c \u2590\u2588\u2588\u258c\u259d\u2588\u2588\u2599\u2588\u2588\u259b",
    "    \u2597\u259f\u2588\u2588\u2588\u2588\u2584\u259f\u2588\u2588\u2588\u2588\u2584       \u2590\u2588\u2588\u259b\u2588\u2588\u258c  \u2588\u2588  \u2590\u2588\u258c\u2590\u2588\u2588\u258c \u2590\u2588\u2588\u258c \u259d\u2588\u2588\u2588\u259b",
    "   \u2584\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2599\u2596     \u2588\u2588\u2588\u2584\u2588\u2588\u2588  \u2588\u2588\u2588\u2588\u2588\u2588 \u2590\u2588\u2588\u258c \u2590\u2588\u2588\u258c  \u259f\u2588\u2588\u2596",
    "  \u2590\u2588\u2588\u2588\u2588\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u259c\u2588\u2588\u2588\u2588    \u2590\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u258c \u2588\u2588\u2599\u2584\u2584\u2584\u2596\u2590\u2588\u2588\u2599\u2596\u2590\u2588\u2588\u258c \u259f\u2588\u2588\u2588\u2588\u2596",
    " \u259f\u2588\u2588\u2588\u259b         \u259d\u2588\u2588\u2588\u2588\u2596  \u2588\u2588\u2588   \u259c\u2588\u2588 \u259c\u2588\u2588\u2588\u2588\u2588 \u2590\u2588\u2588\u2588\u258c\u2590\u2588\u2588\u258c\u259f\u2588\u2588\u2598\u259c\u2588\u2588",
)

LOGO_ART = "\n".join(_LOGO_LINES)
"""The multi-line block art, no colour (no trailing newline)."""

LOGO_ANSI = "\n".join((
    "    \x1b[38;2;14;116;144m\u259d\u2588\u2588\u2588\u2588\u2596  \x1b[38;2;30;207;234m\u259f\x1b[38;2;34;211;238m\u2588\u2588\u2588\u259b\x1b[0m",
    "     \x1b[38;2;14;116;144m\u259d\u259c\u2588\u2588\u2588\u2584\x1b[38;2;30;207;234m\u259f\u2588\u2588\u2588\x1b[38;2;34;211;238m\u2580\x1b[0m",
    "       \x1b[38;2;14;116;144m\u259c\u2588\u2588\x1b[38;2;26;203;231m\u2588\u2588\u2588\x1b[38;2;30;207;234m\u2588\u2598                               \x1b[38;2;34;211;238m\u2588\u2588\x1b[0m",
    "        \x1b[38;2;14;116;144m\u259c\x1b[38;2;22;199;227m\u2588\u2588\x1b[38;2;26;203;231m\u2588\u2588\u2598            \x1b[38;2;246;250;251m\u2588\u2588\u2588           \u2590\u2588\u2588\u258c  \x1b[38;2;34;211;238m\u2588\u2588\x1b[0m",
    "       \x1b[38;2;18;194;223m\u259f\x1b[38;2;22;199;227m\u2588\u2588\u2588\u2588\x1b[38;2;14;116;144m\u2588\u2588\u2596          \x1b[38;2;246;250;251m\u2590\u2588\u2588\u2588\u258c   \u2597\u2584\u2584\u2584\u2584\u2584 \u2590\u2588\u2588\u258c \u2597\u2584\u2584\u2596\u2584\u2584\u2584 \u2597\u2584\u2584\x1b[0m",
    "      \x1b[38;2;18;194;223m\u259f\u2588\u2588\u2588\x1b[38;2;22;199;227m\u259b\x1b[38;2;14;116;144m\u2588\u2588\u2588\u2588\u2596         \x1b[38;2;246;250;251m\u2588\u2588\u2588\u2588\u2588   \u2588\u2588\u2580\u2580\u259c\u2588\u258c\u2590\u2588\u2588\u258c \u2590\u2588\u2588\u258c\u259d\u2588\u2588\u2599\u2588\u2588\u259b\x1b[0m",
    "    \x1b[38;2;14;116;144m\u2597\u259f\u2588\u2588\u2588\u2588\u2584\u259f\u2588\u2588\u2588\u2588\u2584       \x1b[38;2;246;250;251m\u2590\u2588\u2588\u259b\u2588\u2588\u258c  \u2588\u2588  \u2590\u2588\u258c\u2590\u2588\u2588\u258c \u2590\u2588\u2588\u258c \u259d\u2588\u2588\u2588\u259b\x1b[0m",
    "   \x1b[38;2;14;116;144m\u2584\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2599\u2596     \x1b[38;2;246;250;251m\u2588\u2588\u2588\u2584\u2588\u2588\u2588  \u2588\u2588\u2588\u2588\u2588\u2588 \u2590\u2588\u2588\u258c \u2590\u2588\u2588\u258c  \u259f\u2588\u2588\u2596\x1b[0m",
    "  \x1b[38;2;14;116;144m\u2590\u2588\u2588\u2588\u2588\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u259c\u2588\u2588\u2588\u2588    \x1b[38;2;246;250;251m\u2590\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u258c \u2588\u2588\u2599\u2584\u2584\u2584\u2596\u2590\u2588\u2588\u2599\u2596\u2590\u2588\u2588\u258c \u259f\u2588\u2588\u2588\u2588\u2596\x1b[0m",
    " \x1b[38;2;6;182;212m\u259f\u2588\u2588\x1b[38;2;10;186;216m\u2588\u259b         \x1b[38;2;14;116;144m\u259d\u2588\u2588\u2588\u2588\u2596  \x1b[38;2;246;250;251m\u2588\u2588\u2588   \u259c\u2588\u2588 \u259c\u2588\u2588\u2588\u2588\u2588 \u2590\u2588\u2588\u2588\u258c\u2590\u2588\u2588\u258c\u259f\u2588\u2588\u2598\u259c\u2588\u2588\x1b[0m",
))
"""The block art with embedded 24-bit truecolor SGR escapes."""

# The mark alone, for terminals too narrow to fit the lockup.
_NARROW_LINES = (
    "  \u259d\u2588\u2588\u2599\u2597\u2588\u2588\u259b",
    "   \u259d\u259c\u2588\u2588\u2588\u2580",
    "    \u259f\u2588\u2588\u2588\u2596",
    "   \u259f\u2588\u2588\u259c\u2588\u2588\u2596",
    "  \u259f\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2596",
    "\u2597\u2588\u2588\u259b\u2580\u2580\u2580\u2580\u2580\u2588\u2588\u2599",
)

LOGO_ART_NARROW = "\n".join(_NARROW_LINES)
"""The mark-only art, no colour."""

LOGO_ANSI_NARROW = "\n".join((
    "  \x1b[38;2;14;116;144m\u259d\u2588\u2588\u2599\x1b[38;2;30;207;234m\u2597\x1b[38;2;34;211;238m\u2588\u2588\u259b\x1b[0m",
    "   \x1b[38;2;14;116;144m\u259d\u259c\u2588\x1b[38;2;26;203;231m\u2588\x1b[38;2;30;207;234m\u2588\u2580\x1b[0m",
    "    \x1b[38;2;22;199;227m\u259f\u2588\u2588\x1b[38;2;14;116;144m\u2588\u2596\x1b[0m",
    "   \x1b[38;2;14;190;219m\u259f\x1b[38;2;18;194;223m\u2588\u2588\x1b[38;2;14;116;144m\u259c\u2588\u2588\u2596\x1b[0m",
    "  \x1b[38;2;14;116;144m\u259f\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2596\x1b[0m",
    "\x1b[38;2;6;182;212m\u2597\u2588\x1b[38;2;14;116;144m\u2588\u259b\u2580\u2580\u2580\u2580\u2580\u2588\u2588\u2599\x1b[0m",
))
"""The mark-only art with truecolor SGR escapes."""

LOGO_WIDTH = 56
"""Columns the full lockup occupies; below this the narrow art is used."""

LOGO_NARROW_WIDTH = 12
"""Columns the mark-only art occupies."""

LOGO_TAGLINE = "Agent Runtime \u00b7 small kernel | extension platform | policy-first execution"
"""Positioning line under the banner. The art already spells the brand name,
so this line does not repeat it."""

LOGO_TAGLINE_NARROW = "Aelix \u00b7 Agent Runtime"
"""Narrow-terminal caption; the mark-only art does not spell the name."""

__all__ = [
    "LOGO_ANSI",
    "LOGO_ANSI_NARROW",
    "LOGO_ART",
    "LOGO_ART_NARROW",
    "LOGO_NARROW_WIDTH",
    "LOGO_TAGLINE",
    "LOGO_TAGLINE_NARROW",
    "LOGO_WIDTH",
]
