"""Aelix umbrella — convenience re-exports across workspace packages.

For tighter dependency footprints, import directly from the per-package
modules (``aelix_ai``, ``aelix_agent_core``, ``aelix_coding_agent``) instead
of from this umbrella.
"""

from aelix_agent_core import (
    Agent,
    AgentOptions,
    AgentState,
    AgentTool,
)
from aelix_agent_core.harness import (
    AgentHarness,
    AgentHarnessOptions,
)
from aelix_ai import (
    AssistantDoneEvent,
    AssistantEndEvent,
    AssistantErrorEvent,
    AssistantMessage,
    AssistantMessageEvent,
    AssistantStartEvent,
    Message,
    Model,
    ProviderResponse,
    SimpleStreamOptions,
    StreamSimpleError,
    TextContent,
    TextDeltaEvent,
    TextEndEvent,
    TextStartEvent,
    ThinkingDeltaEvent,
    ThinkingEndEvent,
    ThinkingStartEvent,
    Tool,
    ToolCallContent,
    ToolCallDeltaEvent,
    ToolCallEndEvent,
    ToolCallStartEvent,
    ToolPartialCallback,
    ToolResult,
    ToolResultMessage,
    UserMessage,
    clear_providers,
    get_registered_providers,
    register_provider,
    register_provider_object,
    unregister_provider,
    unregister_providers_by_source,
)
from aelix_coding_agent.builtin import (
    GuardrailExtension,
    PolicyExtension,
)

__all__ = [
    "Agent",
    "AgentHarness",
    "AgentHarnessOptions",
    "AgentOptions",
    "AgentState",
    "AgentTool",
    "AssistantDoneEvent",
    "AssistantEndEvent",
    "AssistantErrorEvent",
    "AssistantMessage",
    "AssistantMessageEvent",
    "AssistantStartEvent",
    "GuardrailExtension",
    "Message",
    "Model",
    "PolicyExtension",
    "ProviderResponse",
    "SimpleStreamOptions",
    "StreamSimpleError",
    "TextContent",
    "TextDeltaEvent",
    "TextEndEvent",
    "TextStartEvent",
    "ThinkingDeltaEvent",
    "ThinkingEndEvent",
    "ThinkingStartEvent",
    "Tool",
    "ToolCallContent",
    "ToolCallDeltaEvent",
    "ToolCallEndEvent",
    "ToolCallStartEvent",
    "ToolPartialCallback",
    "ToolResult",
    "ToolResultMessage",
    "UserMessage",
    "clear_providers",
    "get_registered_providers",
    "register_provider",
    "register_provider_object",
    "unregister_provider",
    "unregister_providers_by_source",
]
