"""Pi parity: ``packages/coding-agent/src/modes/rpc`` facade re-exports.

Maps to Pi's ``modes/index.ts`` exports (``runRpcMode``, ``RpcClient``,
``RpcCommand``, ``RpcResponse``, ``RpcSessionState``).

Sprint 6d C2 (rpc_mode) ships the server-side surface; the
:class:`RpcClient` re-export lands together with the client module in
the next commit.
"""

from __future__ import annotations

from aelix_coding_agent.rpc._jsonl import (
    JsonlLineReader,
    attach_jsonl_line_reader,
    serialize_json_line,
)
from aelix_coding_agent.rpc.rpc_mode import (
    DEFERRED_COMMANDS,
    SUPPORTED_COMMANDS,
    build_dispatch_table,
    run_rpc_mode,
)
from aelix_coding_agent.rpc.rpc_types import (
    RPC_COMMAND_TYPES,
    RPC_EXTENSION_UI_REQUEST_METHODS,
    RpcCommand,
    RpcCommandAbort,
    RpcCommandAbortBash,
    RpcCommandAbortRetry,
    RpcCommandBash,
    RpcCommandClone,
    RpcCommandCompact,
    RpcCommandCycleModel,
    RpcCommandCycleThinkingLevel,
    RpcCommandExportHtml,
    RpcCommandFollowUp,
    RpcCommandFork,
    RpcCommandGetAvailableModels,
    RpcCommandGetCommands,
    RpcCommandGetForkMessages,
    RpcCommandGetLastAssistantText,
    RpcCommandGetMessages,
    RpcCommandGetSessionStats,
    RpcCommandGetState,
    RpcCommandNewSession,
    RpcCommandPrompt,
    RpcCommandSetAutoCompaction,
    RpcCommandSetAutoRetry,
    RpcCommandSetFollowUpMode,
    RpcCommandSetModel,
    RpcCommandSetSessionName,
    RpcCommandSetSteeringMode,
    RpcCommandSetThinkingLevel,
    RpcCommandSteer,
    RpcCommandSwitchSession,
    RpcErrorResponse,
    RpcExtensionUIRequest,
    RpcExtensionUIRequestConfirm,
    RpcExtensionUIRequestEditor,
    RpcExtensionUIRequestInput,
    RpcExtensionUIRequestNotify,
    RpcExtensionUIRequestSelect,
    RpcExtensionUIRequestSetEditorText,
    RpcExtensionUIRequestSetStatus,
    RpcExtensionUIRequestSetTitle,
    RpcExtensionUIRequestSetWidget,
    RpcExtensionUIResponse,
    RpcExtensionUIResponseCancelled,
    RpcExtensionUIResponseConfirmed,
    RpcExtensionUIResponseValue,
    RpcResponse,
    RpcSessionState,
    RpcSlashCommand,
    RpcSuccessResponse,
    command_to_json,
    parse_rpc_command,
    parse_rpc_response,
)

__all__ = [
    "DEFERRED_COMMANDS",
    "JsonlLineReader",
    "RPC_COMMAND_TYPES",
    "RPC_EXTENSION_UI_REQUEST_METHODS",
    "RpcCommand",
    "RpcCommandAbort",
    "RpcCommandAbortBash",
    "RpcCommandAbortRetry",
    "RpcCommandBash",
    "RpcCommandClone",
    "RpcCommandCompact",
    "RpcCommandCycleModel",
    "RpcCommandCycleThinkingLevel",
    "RpcCommandExportHtml",
    "RpcCommandFollowUp",
    "RpcCommandFork",
    "RpcCommandGetAvailableModels",
    "RpcCommandGetCommands",
    "RpcCommandGetForkMessages",
    "RpcCommandGetLastAssistantText",
    "RpcCommandGetMessages",
    "RpcCommandGetSessionStats",
    "RpcCommandGetState",
    "RpcCommandNewSession",
    "RpcCommandPrompt",
    "RpcCommandSetAutoCompaction",
    "RpcCommandSetAutoRetry",
    "RpcCommandSetFollowUpMode",
    "RpcCommandSetModel",
    "RpcCommandSetSessionName",
    "RpcCommandSetSteeringMode",
    "RpcCommandSetThinkingLevel",
    "RpcCommandSteer",
    "RpcCommandSwitchSession",
    "RpcErrorResponse",
    "RpcExtensionUIRequest",
    "RpcExtensionUIRequestConfirm",
    "RpcExtensionUIRequestEditor",
    "RpcExtensionUIRequestInput",
    "RpcExtensionUIRequestNotify",
    "RpcExtensionUIRequestSelect",
    "RpcExtensionUIRequestSetEditorText",
    "RpcExtensionUIRequestSetStatus",
    "RpcExtensionUIRequestSetTitle",
    "RpcExtensionUIRequestSetWidget",
    "RpcExtensionUIResponse",
    "RpcExtensionUIResponseCancelled",
    "RpcExtensionUIResponseConfirmed",
    "RpcExtensionUIResponseValue",
    "RpcResponse",
    "RpcSessionState",
    "RpcSlashCommand",
    "RpcSuccessResponse",
    "SUPPORTED_COMMANDS",
    "attach_jsonl_line_reader",
    "build_dispatch_table",
    "command_to_json",
    "parse_rpc_command",
    "parse_rpc_response",
    "run_rpc_mode",
    "serialize_json_line",
]
