"""Pi parity: ``packages/coding-agent/src/modes/rpc/rpc-client.ts`` (343 LOC).

:class:`RpcClient` spawns the Aelix CLI as a subprocess with ``--mode rpc``,
wraps stdin/stdout with JSONL framing, correlates responses by ``id``, and
broadcasts session events to listeners.

Pi parity invariants:

- 100 ms startup grace before failing if the child exited (Pi
  ``rpc-client.ts:81``).
- 30 s send timeout per command (Pi ``rpc-client.ts:332``).
- 60 s ``waitForIdle`` default (Pi ``rpc-client.ts:262``).
- SIGTERM → wait 1 s → SIGKILL (Pi ``rpc-client.ts:107-122``).
- ``id`` generated by monotonic counter (Pi ``requestId``).
- ``pending_requests: dict[id, Future]`` correlation map.

The Sprint 6d Python client ports the **full 29-method command surface** —
deferred commands receive the server's :class:`RpcErrorResponse` and raise
:class:`RpcClientError` so callers see Pi-shape failure semantics today.

AELIX-ORIGINAL DIVERGENCES, all deliberate and all measured against the pin
-------------------------------------------------------------------------

pi's ``rpc-client.ts`` (515 lines at ``734e08e``) has **two** ``.on(`` calls in
the whole file: stderr ``data``, and an ``exit`` handler that lives *inside*
``stop()``. Its only liveness check is the same one-shot 100 ms grace ported
above. Everything below is therefore hardening aelix adds, not parity aelix
restores, and the distinction belongs in the ADR:

1. **Child-death detection** (:meth:`RpcClient._watch_for_exit`). Without it a
   child that dies at any point past the grace window costs the caller its
   FULL budget — measured, a child exiting at 400 ms left
   ``prompt_and_wait(timeout_ms=5000)`` blocked for 5.02 s and then raised a
   bare ``TimeoutError()`` with empty args, while ``proc.returncode == 7`` had
   been readable the entire time. At ``DEFAULT_WAIT_FOR_IDLE_MS`` that is 60 s,
   and a delegation budget would make it ten minutes. The real reasons a real
   child dies — a bad ``--tools`` name, no API key, an import error, an
   OOM-kill — all land outside the 100 ms window.

2. **Containment** (``containment_spawn_kwargs``, the ``preexec_fn`` seam).
   Without a group of its own the child joins the PARENT's process group, so one
   Ctrl+C SIGINTs every rpc child at once and nothing converts that into a
   response. The death signal itself is a POLICY the caller injects, because
   the implementation lives in the bundled extension and product-core may not
   import it (ADR-0197 §(a), the import-direction gate).

   #202 made that containment reach the whole TREE and gave it a Windows twin
   (``aelix_ai.utils._process_tree``, ADR-0238). POSIX is unchanged in shape —
   ``start_new_session=True`` — and :meth:`RpcClient.stop`'s soft stage is still
   a ``SIGTERM`` at the ROOT. ``killpg`` is the ESCALATION, so a descendant the
   child left behind dies with the group only when the child did NOT take the
   soft hint. On the cooperative path nothing group-wide is sent at all and a
   non-``setsid`` leftover of the child survives on POSIX — ``close()`` is a
   release there, never a kill. Measured: a pipe-holding grandchild outlives
   ``stop()``, on ``main`` and here alike (review posix2/F2). On Windows
   ``start_new_session`` was silently ignored (CPython names the parameter
   ``unused_start_new_session``) and ``terminate()`` was an uncatchable
   ``TerminateProcess`` that orphaned every descendant, every time; the child is
   now spawned ``CREATE_NEW_PROCESS_GROUP`` so :meth:`RpcClient.stop`'s
   ``CTRL_BREAK_EVENT`` has an address, and held by a Job Object. The tree is
   attached with ``kill_on_close=True`` — this client owns exactly one child per
   task, so releasing the tree is the same event as being done with it, and it
   is what ends there the leftovers POSIX keeps. That also makes the child die
   with its parent on Windows — the same guarantee Linux gives when the caller
   injects ``pdeathsig`` through the ``preexec_fn`` seam, and one POSIX
   otherwise has no way to offer. Subprocess hooks and ``!command`` ask for the
   opposite, because a hook may background a helper deliberately and exit 0
   over it.

3. **The argv/env/stderr seams.** ``RpcClientOptions`` grew ``argv`` and
   ``env_base`` so a caller can supply a COMPLETE command line and a COMPLETE
   environment. ``env`` alone could not express a DELETION, which made the
   mandatory ``AELIX_MCP_CONFIG`` pop inexpressible — every child would
   otherwise fan out its own copy of every configured MCP server.

4. **``Stderr:`` on the idle timeouts.** This one is the opposite of a
   divergence: pi attaches it (``rpc-client.ts:405``, ``:426``) and aelix
   already did in ``_send``, but the three ``wait_for`` calls were bare.

WHAT IS **NOT** FIXED HERE, AND WHY
-----------------------------------

``agent_end`` carries no correlation id — no session event does. So two
overlapping turns on ONE client cannot be told apart, and a stale terminator
resolves the wrong waiter (measured: a delegation returned another's answer,
usage and terminator with ``ok=True`` in a fifth of its own runtime). **pi has
the identical defect** (``rpc-client.ts:429-432``, ``:458-468``); it was simply
unreachable there because pi never ran two delegations through one client.

It is not solvable on this side of the wire: the abandoned turn emits
``agent_start`` *and* ``agent_end`` after the second waiter subscribes, so no
client-side epoch or pairing can separate them. The two fixes that do work are
both elsewhere and both in place — the server's busy preflight rejects the
second ``prompt`` outright, and ``RpcChannel`` gives every task its own child.
Do not add a client-side "fix" here that only appears to work.
"""

from __future__ import annotations

import asyncio
import contextlib
import itertools
import json
import os
import signal as _signal
import sys
import time
from collections.abc import Callable, Mapping
from dataclasses import dataclass, field
from typing import Any

from aelix_ai.utils._process_tree import (
    ProcessTree,
    _retained_handle,
    containment_spawn_kwargs,
    kill_process_tree,
)

from aelix_coding_agent.rpc._jsonl import (
    JsonlLineReader,
    pump_jsonl_lines,
    serialize_json_line,
)
from aelix_coding_agent.rpc.rpc_types import (
    RpcErrorResponse,
    RpcSessionState,
    RpcSlashCommand,
    RpcSuccessResponse,
    parse_rpc_response,
)


class RpcClientError(RuntimeError):
    """Raised when the RPC server returns ``success: false``.

    The error message is the server-supplied string verbatim (Pi parity:
    ``rpc-client.ts:336`` throws an ``Error`` with the server's ``error``).
    Use :attr:`command` to dispatch on which command failed.
    """

    def __init__(self, command: str, message: str) -> None:
        super().__init__(message)
        self.command = command


class RpcServerExited(RuntimeError):
    """The child RPC server process is gone — aelix-original (see module doc).

    Raised instead of letting the caller block for its whole budget, and
    deliberately a ``RuntimeError`` subclass so the one shape any existing
    caller could have caught (``start``'s premature-exit raise, which was a
    bare ``RuntimeError``) still matches.

    :param returncode: the child's exit status, or ``None`` if the process is
        gone but the status was never observed.
    :param stderr: everything the child wrote to stderr. THIS IS THE POINT —
        an rpc child that dies during startup writes its traceback here and
        nothing at all to stdout, so without it the failure is undiagnosable.
    """

    def __init__(
        self, message: str, *, returncode: int | None = None, stderr: str = ""
    ) -> None:
        super().__init__(message)
        self.returncode = returncode
        self.stderr = stderr


@dataclass
class RpcClientOptions:
    """Pi parity: ``rpc-client.ts:RpcClientOptions``, plus the aelix seams.

    The first six fields are pi's. The rest exist because a delegation channel
    has to decide argv, environment and containment itself, and the ADR-0197
    band rule puts every one of those DECISIONS in the bundled extension while
    keeping the MECHANISM here. Each defaults to "behave exactly as before".
    """

    cli_path: str | None = None
    cwd: str | None = None
    env: dict[str, str] = field(default_factory=dict)
    provider: str | None = None
    model: str | None = None
    args: list[str] = field(default_factory=list)

    argv: list[str] | None = None
    """The COMPLETE command line, replacing :meth:`RpcClient._build_argv`.

    When set, ``cli_path`` / ``provider`` / ``model`` / ``args`` are ignored —
    a caller that renders its own argv has already decided all of them, and
    silently appending to a fully-specified command line is how a child ends up
    running flags nobody chose.

    The default argv is ``python -m aelix --mode rpc``, which points at the
    umbrella package's **mock-echo demo** (``src/aelix/__main__.py:144-148``),
    not the real CLI. Any caller wanting a real child must use this field;
    ``cli_path`` is not an escape, it splices in as a bare script path.
    """

    env_base: Mapping[str, str] | None = None
    """What to build the child's environment FROM. ``None`` means ``os.environ``.

    Exists because ``env`` can only add or overwrite. A caller that must
    REMOVE an inherited key — ``AELIX_MCP_CONFIG`` is the one that matters, or
    every child fans out its own copy of every configured MCP server — cannot
    express that through ``env``: passing ``None`` as a value leaves the key
    present with a ``None`` value, which ``create_subprocess_exec`` rejects.
    """

    preexec_fn: Callable[[], None] | None = None
    """Run in the child between ``fork`` and ``exec``. POSIX only.

    The seam exists so a caller can install a parent-death signal without
    product-core importing the bundled extension, which the import-direction
    gate forbids. Keep whatever goes here async-signal-safe and short.
    """

    stderr_max_bytes: int | None = None
    """Override :attr:`RpcClient.STDERR_MAX_BYTES` for this client.

    A delegation wants a far smaller window than the 10 MiB default: the
    envelope's fallback chain only ever shows a TAIL, and it hands the raw
    capture to an UNCAPPED details field.
    """

    stdout_line_max_bytes: int | None = None
    """Per-line budget for the CHILD's stdout. ``None`` (default) = unbounded.

    Opt-in, and only ever on this direction — see the note on
    :class:`~aelix_coding_agent.rpc._jsonl.JsonlLineReader`.
    """

    raise_on_command_error: bool = False
    """Raise :class:`RpcClientError` when the server answers ``success: false``.

    OFF by default because off IS pi. Measured at the pin: pi's ``send``
    (``rpc-client.ts:474``) returns the raw response, and the throw lives in the
    separate ``getData`` (``:506-508``) — so ``prompt`` / ``steer`` / ``abort``
    and every other void-returning command call ``send`` alone and DISCARD a
    server-side refusal. aelix ports that asymmetry faithfully.

    It is faithful and it is a trap for an automated caller. The rpc server's
    busy preflight refuses a second ``prompt`` with exactly this shape, and a
    caller that discards it then waits for a terminator that will never come —
    turning an immediate, correlated "no" into a full-budget timeout with a
    misleading verdict. Unlike the ``agent_end`` terminator, this answer is
    correlated by request id, so it PROVABLY belongs to the caller.

    Anything driving a child unattended should turn this on.
    """

    send_timeout_ms: int | None = None
    """Override :attr:`RpcClient.DEFAULT_SEND_TIMEOUT_MS` for this client.

    The 30 s default is pi's, and it is dangerously close to a REAL child's
    startup cost: a cold ``--mode rpc`` child measured ~25 s, of which ~18.6 s
    is import time alone. The first command's ack cannot arrive until the child
    reaches its read loop, so a caller spawning a real child is one slow disk
    away from a spurious send timeout. Anything driving a real child should
    raise this to its own budget.
    """

    reader_limit: int | None = None
    """``StreamReader`` buffer ceiling passed to ``create_subprocess_exec``.

    Inert for this client as written (the pump uses ``read``, which never
    consults it — measured), so it is a guard for a future reader that reaches
    for ``readline``, where the default 65536 raises on any longer line AND
    leaves the oversize bytes in the buffer so every subsequent read raises too.
    """


class RpcClient:
    """Pi parity: ``rpc-client.ts:RpcClient``.

    Spawns ``python -m aelix --mode rpc`` (or the configured ``cli_path``)
    as a subprocess. Provides typed methods for every Pi RpcCommand
    variant (29 total). Deferred commands raise :class:`RpcClientError`
    because the server returns :class:`RpcErrorResponse`.
    """

    # Pi parity: ``rpc-client.ts:79`` (100ms), ``:107`` (1s), ``:262``
    # (60s), ``:332`` (30s). Constants are class-level so the closure pin
    # in ``tests/pi_parity/test_phase_4_4_strict_superset.py`` can assert
    # them without instantiating the client.
    DEFAULT_SEND_TIMEOUT_MS: int = 30_000
    DEFAULT_WAIT_FOR_IDLE_MS: int = 60_000
    STARTUP_GRACE_MS: int = 100
    SHUTDOWN_SIGTERM_TIMEOUT_MS: int = 1_000
    # W4 M4 — cap captured stderr at 10 MB so a misbehaving server
    # (verbose stack-trace loop) can't exhaust client memory. Excess
    # bytes are dropped from the FRONT (FIFO) so the most-recent error
    # context is what callers see via ``get_stderr()``.
    STDERR_MAX_BYTES: int = 10 * 1024 * 1024
    # Aelix-original. How often :meth:`_watch_for_exit` reads ``returncode``.
    # An attribute read, not a syscall — asyncio's child watcher sets the field
    # from its own callback — so this is 20 wakeups a second while a child is
    # alive and none at all otherwise. Same value and same reason as the
    # bundled extension's own exit poll.
    #
    # POLLING, NOT ``proc.wait()``, and that distinction is load-bearing:
    # ``wait()`` does not resolve until every PIPE is disconnected, so anything
    # the child leaves behind holding fd 1/2 keeps it pending long after the
    # process is gone (CPython ``asyncio/base_subprocess.py``, ``_try_finish``
    # requires ``all(p.disconnected)``). ``returncode`` is the independent signal.
    EXIT_POLL_SECONDS: float = 0.05

    def __init__(self, options: RpcClientOptions | None = None) -> None:
        self._options = options or RpcClientOptions()
        self._proc: asyncio.subprocess.Process | None = None
        # Assigned in the same statement group as ``_proc`` and never later: on
        # win32 only descendants created AFTER the job assignment inherit
        # membership, so a late attach would contain a different tree than the
        # one that was spawned (#202).
        self._tree: ProcessTree | None = None
        self._stdout_reader_task: asyncio.Task[None] | None = None
        self._stderr_reader_task: asyncio.Task[None] | None = None
        self._exit_watcher_task: asyncio.Task[None] | None = None
        self._stdout_reader: JsonlLineReader | None = None
        self._stderr_buffer: bytearray = bytearray()
        self._event_listeners: list[Callable[[dict[str, Any]], None]] = []
        # Pi parity: requestId numeric monotonic counter, see ``rpc-client.ts:55``.
        self._next_id = itertools.count(1)
        self._pending_requests: dict[
            str, asyncio.Future[RpcSuccessResponse | RpcErrorResponse]
        ] = {}
        # Set by :meth:`_watch_for_exit` the moment ``returncode`` appears, and
        # never cleared while the client is started. Every wait in this class
        # races it, which is what turns "the child died" from a timeout into an
        # immediate, diagnosable failure.
        self._exited: asyncio.Event = asyncio.Event()
        self._stopping = False

    # === Introspection =========================================================

    @property
    def process(self) -> asyncio.subprocess.Process | None:
        """The child process, or ``None`` before :meth:`start` / after :meth:`stop`.

        Published because a caller that owns the child's lifecycle needs the
        real object: the process-tree reaper, the descendant walk and the
        registry row that ``stop_all`` reaches through all take a ``Process``,
        and none of them can be built from this class's public surface.
        """

        return self._proc

    @property
    def tree(self) -> ProcessTree | None:
        """The containment tree :meth:`start` attached.

        ``None`` before :meth:`start` and after :meth:`stop` (and after
        ``start``'s premature-exit path, ``:513-521``); LIVE for the whole started
        window, INCLUDING while :meth:`stop` is running — ``stop`` closes it and
        nulls ``_tree`` only at the very end (``:637-642``), so this property never
        hands out a closed tree.

        Published for the same reason as :attr:`process`: the delegation
        channel's reaper runs DETACHED (finding B1) and must reach the job/group
        the client owns, without owning it. Read it; do not hold it across an
        ``await`` that could reach :meth:`stop`.
        """

        return self._tree

    @property
    def returncode(self) -> int | None:
        """The child's exit status, or ``None`` while it is alive."""

        return self._proc.returncode if self._proc is not None else None

    @property
    def dropped_lines(self) -> int:
        """Oversize stdout lines discarded by the framing budget.

        Always 0 unless :attr:`RpcClientOptions.stdout_line_max_bytes` was set.
        Readable WHILE the pump runs, which is why the reader is owned here
        rather than being a local inside it.
        """

        return self._stdout_reader.dropped_lines if self._stdout_reader else 0

    def _stderr_cap(self) -> int:
        override = self._options.stderr_max_bytes
        return override if override is not None else self.STDERR_MAX_BYTES

    def _send_timeout_s(self) -> float:
        override = self._options.send_timeout_ms
        ms = override if override is not None else self.DEFAULT_SEND_TIMEOUT_MS
        return ms / 1000.0

    async def wait_for_exit(self, timeout: float | None = None) -> int | None:
        """Block until the child is gone. Returns its status, ``None`` on timeout.

        Self-sufficient by design — it polls ``returncode`` itself rather than
        leaning on :meth:`_watch_for_exit`'s event, so it still answers after
        :meth:`stop` has torn the watcher down.

        NOT ``proc.wait()``: that resolves only once every pipe is disconnected,
        so a descendant holding the child's stdio keeps it pending long after
        the process is gone. ``returncode`` is the independent signal.
        """

        proc = self._proc
        if proc is None:
            return None
        deadline = None if timeout is None else time.monotonic() + timeout
        while proc.returncode is None:
            if deadline is not None and time.monotonic() >= deadline:
                return None
            await asyncio.sleep(self.EXIT_POLL_SECONDS)
        return proc.returncode

    async def drain(self, timeout: float) -> None:
        """Give the pumps a bounded chance to reach EOF. Never raises.

        For the caller that kills a child mid-turn: the dying child's last
        bytes are still in the pipe, and they are the partial answer worth
        reporting. Bounded because a pump blocked on a pipe some survivor still
        holds must not convert a finished delegation into a hang.
        """

        tasks = [
            task
            for task in (self._stdout_reader_task, self._stderr_reader_task)
            if task is not None
        ]
        if not tasks:
            return
        with contextlib.suppress(Exception):
            await asyncio.wait(tasks, timeout=timeout)

    # === Lifecycle =============================================================

    async def start(self) -> None:
        """Pi parity: ``rpc-client.ts:60-83`` (``start``)."""

        if self._proc is not None:
            raise RuntimeError("RpcClient already started")

        argv = self._build_argv()
        env = self._build_env()
        opts = self._options

        spawn_kwargs: dict[str, Any] = {}
        if opts.reader_limit is not None:
            spawn_kwargs["limit"] = opts.reader_limit
        if opts.preexec_fn is not None:
            # ``noqa`` mirrors the bundled extension's own spawn: the check
            # exists because a preexec_fn is unsafe in a THREADED parent, and
            # the contract on this seam is that the callable is
            # async-signal-safe.
            spawn_kwargs["preexec_fn"] = opts.preexec_fn  # noqa: PLW1509
        # AELIX-ORIGINAL. Without it the child joins the PARENT's process
        # group, so a single Ctrl+C SIGINTs every rpc child at once — and
        # neither an interactive parent nor an rpc child installs a SIGINT
        # handler, so nothing converts that into a response or an envelope.
        # Measured safe against the whole rpc suite before it was adopted.
        # ``new_session=True`` is ``start_new_session`` on POSIX, unchanged; on
        # win32 it is ``CREATE_NEW_PROCESS_GROUP``, which is the group
        # :meth:`stop`'s ``CTRL_BREAK_EVENT`` is addressed to (#202).
        spawn_kwargs.update(containment_spawn_kwargs(new_session=True))

        self._exited = asyncio.Event()
        self._stopping = False
        self._proc = await asyncio.create_subprocess_exec(
            *argv,
            cwd=opts.cwd,
            env=env,
            stdin=asyncio.subprocess.PIPE,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
            **spawn_kwargs,
        )
        # BEFORE the first ``await``, per :meth:`ProcessTree.attach`: on win32
        # the job is created and assigned here, and only descendants spawned
        # after the assignment inherit membership. ``handle`` is the one the
        # transport already retains, so the assignment never has to re-derive
        # one from the pid and cannot be refused ``ACCESS_DENIED`` (#202).
        self._tree = ProcessTree.attach(
            self._proc.pid, kill_on_close=True, handle=_retained_handle(self._proc)
        )

        proc_stdout = self._proc.stdout
        proc_stderr = self._proc.stderr
        if proc_stdout is None or proc_stderr is None:
            raise RuntimeError("Subprocess pipes are not connected")

        # The reader is OWNED here, not built inside the pump, so
        # ``dropped_lines`` is readable while the pump is still running.
        self._stdout_reader = JsonlLineReader(
            self._handle_stdout_line, max_line_bytes=opts.stdout_line_max_bytes
        )
        self._stdout_reader_task = asyncio.create_task(
            pump_jsonl_lines(proc_stdout, self._stdout_reader)
        )
        self._stderr_reader_task = asyncio.create_task(
            self._drain_stderr(proc_stderr)
        )
        # Started BEFORE the grace window so the window itself is observed by
        # the same mechanism as everything after it.
        self._exit_watcher_task = asyncio.create_task(self._watch_for_exit())

        # Pi parity: 100ms startup grace (``rpc-client.ts:103-108``). It catches
        # exec-level failures only — a real child's boot is two orders of
        # magnitude longer than this (~25 s cold, ~18.6 s of it import time), so
        # anything that fails during startup lands OUTSIDE the window and is
        # caught by :meth:`_watch_for_exit` instead.
        with contextlib.suppress(TimeoutError):
            await asyncio.wait_for(
                self._exited.wait(), timeout=self.STARTUP_GRACE_MS / 1000.0
            )
        if self._exited.is_set():
            returncode = self._proc.returncode
            stderr_snapshot = self.get_stderr()
            await self._teardown_tasks()
            # The child is already gone, but the job handle is not: release it
            # here or the only thing that ever would is the finalizer.
            if self._tree is not None:
                self._tree.close()
            self._tree = None
            self._proc = None
            raise RpcServerExited(
                f"RPC server exited prematurely with code {returncode}. "
                f"Stderr: {stderr_snapshot}",
                returncode=returncode,
                stderr=stderr_snapshot,
            )

    async def stop(self) -> None:
        """Pi parity: ``rpc-client.ts:88-122`` (``stop``).

        Soft → grace → hard, per platform (``aelix_ai.utils._process_tree``,
        #202). POSIX: ``SIGTERM`` at the ROOT → wait 1 s → ``killpg(SIGKILL)``.
        The group kill belongs to the ESCALATION ONLY — a child that takes the
        soft hint is never signalled group-wide, so its non-``setsid``
        leftovers survive here and ``close()`` does not touch them (review
        posix2/F2, posix2/F3). Windows: ``CTRL_BREAK_EVENT``, which is
        group-wide by construction → wait 1 s → ``taskkill /T /F`` plus
        ``TerminateJobObject``, and ``close()`` ends the rest because this tree
        asked for ``kill_on_close``. ``pending_requests`` are cleared so callers
        awaiting :meth:`send` see ``CancelledError`` propagate.

        NOT ``proc.terminate()`` / ``proc.kill()``. Both begin with
        ``Popen.send_signal``'s ``self.poll()`` — a ``waitpid(WNOHANG)`` that
        can reap a just-exited child out from under asyncio's watcher, which
        then reports 255 (measured in ``reaper._signal_child``: ``{255: 60}``).
        The soft and hard stages signal by pid/pgid instead. The trailing
        ``transport.close()`` below still reaches ``Popen.poll()`` and
        ``Popen.kill()`` (CPython ``asyncio/base_subprocess.py``), but that is
        asyncio's own last resort rather than this method's escalation: it can
        only fire for a child that outlived BOTH waits, by which point the reap
        race costs nothing (review posix2/F8, MUT-8).
        """

        proc = self._proc
        if proc is None:
            return

        tree = self._tree
        self._stopping = True
        self._fail_pending(RpcClientError("rpc", "RPC server stopped"))

        # ``returncode`` read immediately before the soft kill with no ``await``
        # in between. THE BOOL IS LOAD-BEARING: ``soft_kill`` returns whether
        # the signal was actually SENT, and a signal that was not sent has
        # nothing to wait for — no attached console on win32
        # (``GenerateConsoleCtrlEvent`` fails, which is the runner shape #202's
        # review flagged), or ``ESRCH`` because the child went in the gap. In
        # both of those the grace below would buy a full second of nothing, so
        # the escalation is taken immediately instead (review win-leg/F2).
        # Staying ``False`` when the child is ALREADY reaped is deliberate too:
        # nothing was attempted, so ``_await_exit`` answers True on its first
        # poll and the escalation is skipped, which is what keeps a dead child's
        # teardown free.
        soft_kill_refused = False
        if proc.returncode is None and tree is not None:
            soft_kill_refused = not tree.soft_kill()
        # POLL ``returncode``, NEVER ``await proc.wait()``. Measured: with a
        # descendant holding the child's stdout/stderr, ``wait()`` does not
        # resolve until those pipes disconnect, so ``stop()`` paid the FULL
        # 1.00 s SIGTERM grace on a child that had already died — while
        # ``returncode`` was set the whole time. Without a holder both shapes
        # return in 0.00 s, which is why the bug survived: only the pipe-holder
        # case is slow, and only that case reproduces it.
        if soft_kill_refused or not await self._await_exit(
            self.SHUTDOWN_SIGTERM_TIMEOUT_MS / 1000.0
        ):
            # Deliberately NOT guarded by root liveness: leader dead and
            # descendants alive is the exact shape the group/job kill exists
            # for, and a guard would skip it.
            #
            # WHAT BOUNDS THE STALE-NUMBER HAZARD IS THE GROUP, NOT THE POLL.
            # An older comment here claimed "the last 50 ms poll saw
            # ``returncode is None``", which is not a bound: asyncio's child
            # watcher calls ``waitpid`` on its own thread and a LATER loop
            # callback copies the status into ``returncode``, so the kernel can
            # have released the pid while ``returncode`` still reads ``None``
            # (measured: a loop blocked 1.5 s read ``None`` for a pid that was
            # already gone). The honest window is (watcher reap → loop callback
            # latency) + the grace. What actually holds is that a NON-EMPTY
            # process group's id cannot be reused while any member lives
            # (POSIX.1 §3.293; Linux holds it through
            # ``attach_pid(PIDTYPE_PGID)``), and an empty one has nothing to
            # kill — ``killpg`` answers ``ESRCH``. The residual case (empty
            # group, number recycled, and its new holder having made itself a
            # group leader inside that window) is accepted and stated in
            # ADR-0238 (review posix2/F4).
            if tree is not None:
                tree.hard_kill()
            else:
                # Reachable only if ``attach`` itself raised out of ``start``,
                # which leaves ``_proc`` set and no tree behind it. Nothing in
                # the product can make it raise; the pid-only kill is here so
                # that shape degrades to a root-and-group kill rather than to
                # an ``AttributeError`` during teardown.
                kill_process_tree(proc.pid)
            # W4 m9 — bound the final reap so a stuck child can't block
            # ``stop()`` forever. 5s is enough for a normal exit and
            # leaves the failure path observable via stderr capture.
            await self._await_exit(5.0)

        await self._teardown_tasks()
        # Closing the transport is what keeps asyncio from printing
        # ``Exception ignored in BaseSubprocessTransport.__del__ ...
        # RuntimeError: Event loop is closed`` at interpreter shutdown — a
        # traceback for a teardown that went exactly as designed, which in a
        # TUI is indistinguishable from a real one and which the user cannot
        # act on. Best-effort: the transport is private and may already be gone.
        with contextlib.suppress(Exception):
            transport = getattr(proc, "_transport", None)
            if transport is not None:
                transport.close()

        # A RELEASE, not a kill: on POSIX this signals nothing at all (the gap
        # between a child's reap and this call is seconds at the delegation
        # caller, which is precisely when an empty group's number is free for
        # somebody else). On win32 it is ``CloseHandle(job)``, and because this
        # tree asked for ``kill_on_close`` it also ends whatever is left.
        if tree is not None:
            tree.close()
        self._tree = None
        self._proc = None
        # The reader is deliberately NOT dropped: ``dropped_lines`` has to
        # survive teardown or the delegation envelope, which is built after the
        # child is gone, always reports zero. ``get_stderr()`` already outlives
        # ``stop`` for the same reason, and the two should not disagree.

    async def close_stdin(self) -> None:
        """Send EOF on the command channel — the GRACEFUL shutdown.

        ``run_rpc_mode`` races a shutdown event against stdin EOF and returns
        when either fires, so closing this pipe asks the child to finish and
        exit on its own, with no signal and no grace window. A caller that owns
        the child for exactly one task should prefer this to :meth:`stop` and
        keep the signal path for the child that does not take the hint.

        Idempotent and never raises: a child that already died closed this end
        for us, which is not an error at the point we are trying to close it.
        """

        proc = self._proc
        if proc is None or proc.stdin is None:
            return
        with contextlib.suppress(Exception):
            proc.stdin.close()

    async def _watch_for_exit(self) -> None:
        """Set :attr:`_exited` the moment the child's status appears.

        AELIX-ORIGINAL; pi has no equivalent (see the module docstring). This
        is the whole child-death mechanism: everything else just races the
        event this sets.

        Pending requests are failed here rather than left to time out, because
        the two legs otherwise disagree by a factor of 5000 — measured, a
        command issued to an already-dead child raised ``RuntimeError`` in
        0.00 s (broken stdin) while one issued just before it died blocked the
        full budget and raised a bare ``TimeoutError``. Same cause, same fact
        about the world, two unrecognisably different failures.
        """

        proc = self._proc
        if proc is None:
            return
        while proc.returncode is None:
            await asyncio.sleep(self.EXIT_POLL_SECONDS)
        self._exited.set()
        if self._stopping:
            # ``stop`` already failed them with its own, more accurate reason.
            return
        self._fail_pending(
            RpcServerExited(
                f"RPC server exited with code {proc.returncode}. "
                f"Stderr: {self.get_stderr()}",
                returncode=proc.returncode,
                stderr=self.get_stderr(),
            )
        )

    def _fail_pending(self, error: BaseException) -> None:
        """Resolve every in-flight request with ``error`` and forget them.

        W4 M3 — a named exception rather than ``future.cancel()``, which
        delivered a ``CancelledError`` with no context (Pi parity:
        ``rpc-client.ts`` rejects pending promises with a named error).
        """

        for future in self._pending_requests.values():
            if not future.done():
                future.set_exception(error)
        self._pending_requests.clear()

    async def _await_exit(self, timeout: float) -> bool:
        """Wait up to ``timeout`` for the child's status. ``True`` if it landed."""

        with contextlib.suppress(TimeoutError):
            await asyncio.wait_for(self._exited.wait(), timeout=timeout)
        return self._exited.is_set()

    async def _teardown_tasks(self) -> None:
        """Cancel and join the three background tasks. Never raises."""

        tasks = (
            self._stdout_reader_task,
            self._stderr_reader_task,
            self._exit_watcher_task,
        )
        for task in tasks:
            if task is not None:
                task.cancel()
        for task in tasks:
            if task is None:
                continue
            with contextlib.suppress(BaseException):
                await task
        self._stdout_reader_task = None
        self._stderr_reader_task = None
        self._exit_watcher_task = None

    # === Event subscription ====================================================

    def on_event(
        self, listener: Callable[[dict[str, Any]], None]
    ) -> Callable[[], None]:
        """Subscribe to streaming events. Returns an unsubscribe callable."""

        self._event_listeners.append(listener)

        def _unsubscribe() -> None:
            with contextlib.suppress(ValueError):
                self._event_listeners.remove(listener)

        return _unsubscribe

    def get_stderr(self) -> str:
        """Return captured stderr (Pi parity ``getStderr``)."""

        return self._stderr_buffer.decode("utf-8", errors="replace")

    # === Command surface (28 methods, Pi parity) ===============================

    async def prompt(
        self,
        message: str,
        images: list[dict[str, Any]] | None = None,
    ) -> None:
        await self._send({"type": "prompt", "message": message, "images": images})

    async def steer(
        self,
        message: str,
        images: list[dict[str, Any]] | None = None,
    ) -> None:
        await self._send({"type": "steer", "message": message, "images": images})

    async def follow_up(
        self,
        message: str,
        images: list[dict[str, Any]] | None = None,
    ) -> None:
        await self._send(
            {"type": "follow_up", "message": message, "images": images}
        )

    async def abort(self) -> None:
        await self._send({"type": "abort"})

    async def new_session(
        self, parent_session: str | None = None
    ) -> dict[str, Any]:
        response = await self._send(
            {"type": "new_session", "parentSession": parent_session}
        )
        return self._unwrap(response)

    async def get_state(self) -> RpcSessionState:
        response = await self._send({"type": "get_state"})
        data = self._unwrap(response)
        return RpcSessionState.from_json(data)

    async def set_model(self, provider: str, model_id: str) -> dict[str, Any]:
        response = await self._send(
            {"type": "set_model", "provider": provider, "modelId": model_id}
        )
        return self._unwrap(response)

    async def cycle_model(self) -> dict[str, Any] | None:
        response = await self._send({"type": "cycle_model"})
        return self._unwrap(response)

    async def get_available_models(self) -> list[dict[str, Any]]:
        response = await self._send({"type": "get_available_models"})
        data = self._unwrap(response)
        return list(data.get("models", []))

    async def set_thinking_level(self, level: str) -> None:
        await self._send({"type": "set_thinking_level", "level": level})

    async def cycle_thinking_level(self) -> dict[str, Any] | None:
        response = await self._send({"type": "cycle_thinking_level"})
        return self._unwrap(response)

    async def set_steering_mode(self, mode: str) -> None:
        await self._send({"type": "set_steering_mode", "mode": mode})

    async def set_follow_up_mode(self, mode: str) -> None:
        await self._send({"type": "set_follow_up_mode", "mode": mode})

    async def compact(
        self, custom_instructions: str | None = None
    ) -> dict[str, Any]:
        response = await self._send(
            {"type": "compact", "customInstructions": custom_instructions}
        )
        return self._unwrap(response)

    async def set_auto_compaction(self, enabled: bool) -> None:
        await self._send({"type": "set_auto_compaction", "enabled": enabled})

    async def set_auto_retry(self, enabled: bool) -> None:
        await self._send({"type": "set_auto_retry", "enabled": enabled})

    async def abort_retry(self) -> None:
        await self._send({"type": "abort_retry"})

    async def bash(self, command: str) -> dict[str, Any]:
        response = await self._send({"type": "bash", "command": command})
        return self._unwrap(response)

    async def abort_bash(self) -> None:
        await self._send({"type": "abort_bash"})

    async def get_session_stats(self) -> dict[str, Any]:
        response = await self._send({"type": "get_session_stats"})
        return self._unwrap(response)

    async def export_html(
        self, output_path: str | None = None
    ) -> dict[str, Any]:
        response = await self._send(
            {"type": "export_html", "outputPath": output_path}
        )
        return self._unwrap(response)

    async def switch_session(self, session_path: str) -> dict[str, Any]:
        response = await self._send(
            {"type": "switch_session", "sessionPath": session_path}
        )
        return self._unwrap(response)

    async def fork(self, entry_id: str) -> dict[str, Any]:
        response = await self._send({"type": "fork", "entryId": entry_id})
        return self._unwrap(response)

    async def clone(self) -> dict[str, Any]:
        response = await self._send({"type": "clone"})
        return self._unwrap(response)

    async def get_fork_messages(self) -> list[dict[str, Any]]:
        response = await self._send({"type": "get_fork_messages"})
        data = self._unwrap(response)
        return list(data.get("messages", []))

    async def get_last_assistant_text(self) -> str | None:
        response = await self._send({"type": "get_last_assistant_text"})
        data = self._unwrap(response)
        return data.get("text") if isinstance(data, dict) else None

    async def set_session_name(self, name: str) -> None:
        await self._send({"type": "set_session_name", "name": name})

    async def get_messages(self) -> list[dict[str, Any]]:
        response = await self._send({"type": "get_messages"})
        data = self._unwrap(response)
        return list(data.get("messages", []))

    async def get_commands(self) -> list[RpcSlashCommand]:
        response = await self._send({"type": "get_commands"})
        data = self._unwrap(response)
        result: list[RpcSlashCommand] = []
        for entry in data.get("commands", []):
            if not isinstance(entry, dict):
                continue
            result.append(
                RpcSlashCommand(
                    name=entry.get("name", ""),
                    source=entry.get("source", "extension"),
                    description=entry.get("description"),
                    source_info=entry.get("sourceInfo"),
                )
            )
        return result

    # === Utility helpers (Pi parity) ==========================================

    async def wait_for_idle(
        self, timeout_ms: int | None = None
    ) -> None:
        """Pi parity: ``rpc-client.ts:waitForIdle`` (60 s default).

        Resolves when an ``agent_end`` event arrives. Raises
        :class:`asyncio.TimeoutError` on timeout.
        """

        timeout_s = (timeout_ms or self.DEFAULT_WAIT_FOR_IDLE_MS) / 1000.0
        idle = asyncio.get_running_loop().create_future()

        def _listener(event: dict[str, Any]) -> None:
            if event.get("type") == "agent_end" and not idle.done():
                idle.set_result(None)

        unsubscribe = self.on_event(_listener)
        try:
            await self._await_terminator(idle, timeout_s, "agent to become idle")
        finally:
            unsubscribe()

    async def collect_events(
        self, timeout_ms: int | None = None
    ) -> list[dict[str, Any]]:
        """Pi parity: ``rpc-client.ts:collectEvents``."""

        timeout_s = (timeout_ms or self.DEFAULT_WAIT_FOR_IDLE_MS) / 1000.0
        collected: list[dict[str, Any]] = []
        done = asyncio.get_running_loop().create_future()

        def _listener(event: dict[str, Any]) -> None:
            collected.append(event)
            if event.get("type") == "agent_end" and not done.done():
                done.set_result(None)

        unsubscribe = self.on_event(_listener)
        try:
            await self._await_terminator(done, timeout_s, "events")
        finally:
            unsubscribe()
        return collected

    async def prompt_and_wait(
        self,
        message: str,
        images: list[dict[str, Any]] | None = None,
        timeout_ms: int | None = None,
        *,
        collect: bool = True,
    ) -> list[dict[str, Any]]:
        """Pi parity: ``rpc-client.ts:promptAndWait``.

        NOT SAFE FOR TWO OVERLAPPING TURNS on one client — ``agent_end`` has no
        correlation id, so a terminator left over from an abandoned turn
        resolves this one. See the module docstring: the defect is pi's too,
        and the fixes live at the server (busy preflight) and in the caller
        (one child per task), not here.

        ``collect=False`` returns an EMPTY list, never a partial one. It is the
        caller's statement that it will not read the result, not a hint — the
        events are still parsed, still correlated and still fanned out to every
        subscriber, so a reducer wired through :meth:`on_event` sees exactly
        what it saw before.

        The buffer is not a micro-optimisation. It retains every event of the
        turn, and ``message_update`` repeats the whole assistant message on
        every delta, so its size is the turn's length times the answer's — with
        no ceiling anywhere. Measured end to end through ``RpcChannel.run``
        against a child emitting 5 000 updates of 4 KB: peak parent memory
        **25.6 MB** with the buffer and **0.36 MB** without, for a list the only
        production caller discards. The list dies with the call, so it is only
        ever visible as a PEAK — measured after the turn it reads 0.04 MB either
        way, which is why a test that snapshots memory at the end proves
        nothing.

        Collecting IS pi (``promptAndWait`` is literally ``collectEvents`` plus
        ``prompt``, ``rpc-client.ts:443-447``), so the default leaves every
        existing caller byte-identical and the opt-out follows the precedent
        :attr:`RpcClientOptions.raise_on_command_error` set in this file: pi's
        behaviour is the default, and the caller driving a child unattended
        opts out of it.
        """

        # Wire the listener BEFORE sending so we don't miss the
        # ``agent_end`` that fires synchronously in fast-stub scenarios.
        timeout_s = (timeout_ms or self.DEFAULT_WAIT_FOR_IDLE_MS) / 1000.0
        collected: list[dict[str, Any]] = []
        done = asyncio.get_running_loop().create_future()

        def _listener(event: dict[str, Any]) -> None:
            if collect:
                collected.append(event)
            if event.get("type") == "agent_end" and not done.done():
                done.set_result(None)

        unsubscribe = self.on_event(_listener)
        try:
            await self.prompt(message, images)
            await self._await_terminator(done, timeout_s, "agent to become idle")
        finally:
            unsubscribe()
        return collected

    async def _await_terminator(
        self, done: asyncio.Future[Any], timeout_s: float, what: str
    ) -> None:
        """Wait for ``done``, the child's death, or the deadline — first wins.

        The child-death leg is the aelix-original half and the reason this
        helper exists at all: without it, every one of the three public waits
        answers "the child is gone" by blocking for its entire budget and then
        raising a bare ``TimeoutError`` with EMPTY args, which tells the caller
        neither what happened nor that anything is wrong with the child.

        The ``Stderr:`` suffix on the timeout IS pi parity (``rpc-client.ts:405``
        and ``:426`` both attach it, and aelix already did in ``_send``); these
        three calls were simply bare. It is also the rung the delegation
        envelope's fallback chain depends on for a child that exits having
        written zero stdout bytes.
        """

        if self._exited.is_set():
            raise self._exit_error()
        death = asyncio.ensure_future(self._exited.wait())
        try:
            await asyncio.wait(
                {done, death},
                return_when=asyncio.FIRST_COMPLETED,
                timeout=timeout_s,
            )
        finally:
            death.cancel()
            with contextlib.suppress(BaseException):
                await death
        if done.done():
            # The terminator won even if the child died in the same tick; a
            # completed turn is a completed turn.
            done.result()
            return
        if self._exited.is_set():
            raise self._exit_error()
        raise TimeoutError(
            f"Timeout waiting for {what}. Stderr: {self.get_stderr()}"
        )

    def _exit_error(self) -> RpcServerExited:
        returncode = self.returncode
        stderr_snapshot = self.get_stderr()
        return RpcServerExited(
            f"RPC server exited with code {returncode} while the caller was "
            f"waiting for it. Stderr: {stderr_snapshot}",
            returncode=returncode,
            stderr=stderr_snapshot,
        )

    # === Internals ============================================================

    def _build_argv(self) -> list[str]:
        """Pi parity: ``rpc-client.ts:62-72`` argv construction.

        Default: ``python -m aelix --mode rpc``. ``cli_path`` overrides the
        default invocation (e.g. for a custom shim or a one-off stub).
        """

        opts = self._options
        if opts.argv is not None:
            # A caller that renders its own command line has already decided
            # provider/model/args; appending to it would run flags nobody chose.
            return list(opts.argv)
        cli_path = opts.cli_path
        if cli_path is not None:
            argv: list[str] = [sys.executable, cli_path, "--mode", "rpc"]
        else:
            argv = [sys.executable, "-m", "aelix", "--mode", "rpc"]
        if opts.provider:
            argv.extend(["--provider", opts.provider])
        if opts.model:
            argv.extend(["--model", opts.model])
        argv.extend(opts.args)
        return argv

    def _build_env(self) -> dict[str, str]:
        """The child's environment: ``env_base`` (default ``os.environ``) + ``env``.

        ``env_base`` is what makes a DELETION expressible. ``env`` alone can
        only add or overwrite, so a caller that must strip an inherited key
        passes a base it already pruned.
        """

        opts = self._options
        base = os.environ if opts.env_base is None else opts.env_base
        env = dict(base)
        env.update(opts.env)
        return env

    async def _drain_stderr(self, stream: asyncio.StreamReader) -> None:
        """Continuously drain the child's stderr into the capture buffer.

        W4 M4 — buffer is capped at :attr:`STDERR_MAX_BYTES` (10 MB).
        Excess bytes are evicted from the FRONT (FIFO) so the most-recent
        diagnostics survive for ``get_stderr()`` callers.
        """

        cap = self._stderr_cap()
        while True:
            chunk = await stream.read(4096)
            if not chunk:
                return
            self._stderr_buffer.extend(chunk)
            if len(self._stderr_buffer) > cap:
                overflow = len(self._stderr_buffer) - cap
                del self._stderr_buffer[:overflow]

    def _handle_stdout_line(self, line: str) -> None:
        """Pi parity: ``rpc-client.ts:handleLine`` — response vs. event split."""

        if not line.strip():
            return
        try:
            payload = json.loads(line)
        except (json.JSONDecodeError, ValueError):
            # Pi swallows non-JSON lines silently.
            return
        if not isinstance(payload, dict):
            return
        if payload.get("type") == "response":
            request_id = payload.get("id")
            if isinstance(request_id, str) and request_id in self._pending_requests:
                try:
                    response = parse_rpc_response(payload)
                except ValueError:
                    return
                future = self._pending_requests.pop(request_id)
                if not future.done():
                    future.set_result(response)
                return
            # W4 m8 — response arrived AFTER the originating request was
            # timed-out + popped. Log to stderr before falling through to
            # event listeners so operators can correlate the drift.
            if isinstance(request_id, str):
                print(
                    f"[rpc-client] stale response id={request_id!r} "
                    f"command={payload.get('command')!r} (request already "
                    "completed/timed out)",
                    file=sys.stderr,
                    flush=True,
                )
            # Response without a tracked id — surface to event listeners
            # so callers can see protocol drift.
        for listener in list(self._event_listeners):
            # Listener errors are isolated (Pi parity — TS try/catch would
            # have prevented one listener from breaking the others).
            with contextlib.suppress(Exception):  # noqa: BLE001
                listener(payload)

    async def _send(
        self, command: dict[str, Any]
    ) -> RpcSuccessResponse | RpcErrorResponse:
        """Send a command and await the correlated response.

        Pi parity: ``rpc-client.ts:323-343``. Drops ``None`` values from
        the payload so the wire shape matches Pi's TS omits-undefined behavior.
        """

        if self._proc is None or self._proc.stdin is None:
            raise RuntimeError("RpcClient not started")

        request_id = f"req_{next(self._next_id)}"
        payload: dict[str, Any] = {"id": request_id}
        for key, value in command.items():
            if value is None:
                continue
            payload[key] = value

        future: asyncio.Future[
            RpcSuccessResponse | RpcErrorResponse
        ] = asyncio.get_running_loop().create_future()
        self._pending_requests[request_id] = future

        line = serialize_json_line(payload).encode("utf-8")
        try:
            self._proc.stdin.write(line)
            await self._proc.stdin.drain()
        except (BrokenPipeError, ConnectionResetError) as exc:
            # A closed command channel means the server is gone. Normalised to
            # the SAME exception the slow leg raises: measured, this leg fired
            # in 0.00 s as a plain ``RuntimeError`` while a command issued
            # moments earlier blocked the full budget and raised
            # ``TimeoutError`` — one fact about the world, two unrecognisably
            # different failures, and callers handled only whichever they hit
            # first in testing.
            self._pending_requests.pop(request_id, None)
            stderr_snapshot = self.get_stderr()
            raise RpcServerExited(
                f"RPC server closed stdin: {exc}",
                returncode=self.returncode,
                stderr=stderr_snapshot,
            ) from exc

        try:
            await self._await_terminator(
                future,
                self._send_timeout_s(),
                f"response to {command.get('type')!r}",
            )
        except BaseException:
            self._pending_requests.pop(request_id, None)
            raise
        response = future.result()
        if self._options.raise_on_command_error and isinstance(
            response, RpcErrorResponse
        ):
            raise RpcClientError(response.command, response.error)
        return response

    def _unwrap(
        self, response: RpcSuccessResponse | RpcErrorResponse
    ) -> Any:
        """Pi parity: ``rpc-client.ts:getData`` — raise on error, return data otherwise."""

        if isinstance(response, RpcErrorResponse):
            raise RpcClientError(response.command, response.error)
        return response.data


# Some platforms (Windows) lack SIGTERM equivalents; expose for symmetry
# with Pi's ``rpc-client.ts:108`` so callers can verify the constant.
_SIGTERM = getattr(_signal, "SIGTERM", None)


__all__ = [
    "RpcClient",
    "RpcClientError",
    "RpcClientOptions",
    "RpcServerExited",
]
