"""Pi parity: ``packages/coding-agent/src/modes/rpc/rpc-client.ts`` (343 LOC).

:class:`RpcClient` spawns the Aelix CLI as a subprocess with ``--mode rpc``,
wraps stdin/stdout with JSONL framing, correlates responses by ``id``, and
broadcasts session events to listeners.

Pi parity invariants:

- 100 ms startup grace before failing if the child exited (Pi
  ``rpc-client.ts:81``).
- 30 s send timeout per command (Pi ``rpc-client.ts:332``).
- 60 s ``waitForIdle`` default (Pi ``rpc-client.ts:262``).
- SIGTERM → wait 1 s → SIGKILL (Pi ``rpc-client.ts:107-122``).
- ``id`` generated by monotonic counter (Pi ``requestId``).
- ``pending_requests: dict[id, Future]`` correlation map.

The Sprint 6d Python client ports the **full 29-method command surface** —
deferred commands receive the server's :class:`RpcErrorResponse` and raise
:class:`RpcClientError` so callers see Pi-shape failure semantics today.
"""

from __future__ import annotations

import asyncio
import contextlib
import itertools
import json
import os
import signal as _signal
import sys
from collections.abc import Callable
from dataclasses import dataclass, field
from typing import Any

from aelix_coding_agent.rpc._jsonl import (
    attach_jsonl_line_reader,
    serialize_json_line,
)
from aelix_coding_agent.rpc.rpc_types import (
    RpcErrorResponse,
    RpcSessionState,
    RpcSlashCommand,
    RpcSuccessResponse,
    parse_rpc_response,
)


class RpcClientError(RuntimeError):
    """Raised when the RPC server returns ``success: false``.

    The error message is the server-supplied string verbatim (Pi parity:
    ``rpc-client.ts:336`` throws an ``Error`` with the server's ``error``).
    Use :attr:`command` to dispatch on which command failed.
    """

    def __init__(self, command: str, message: str) -> None:
        super().__init__(message)
        self.command = command


@dataclass
class RpcClientOptions:
    """Pi parity: ``rpc-client.ts:RpcClientOptions``."""

    cli_path: str | None = None
    cwd: str | None = None
    env: dict[str, str] = field(default_factory=dict)
    provider: str | None = None
    model: str | None = None
    args: list[str] = field(default_factory=list)


class RpcClient:
    """Pi parity: ``rpc-client.ts:RpcClient``.

    Spawns ``python -m aelix --mode rpc`` (or the configured ``cli_path``)
    as a subprocess. Provides typed methods for every Pi RpcCommand
    variant (29 total). Deferred commands raise :class:`RpcClientError`
    because the server returns :class:`RpcErrorResponse`.
    """

    # Pi parity: ``rpc-client.ts:79`` (100ms), ``:107`` (1s), ``:262``
    # (60s), ``:332`` (30s). Constants are class-level so the closure pin
    # in ``tests/pi_parity/test_phase_4_4_strict_superset.py`` can assert
    # them without instantiating the client.
    DEFAULT_SEND_TIMEOUT_MS: int = 30_000
    DEFAULT_WAIT_FOR_IDLE_MS: int = 60_000
    STARTUP_GRACE_MS: int = 100
    SHUTDOWN_SIGTERM_TIMEOUT_MS: int = 1_000
    # W4 M4 — cap captured stderr at 10 MB so a misbehaving server
    # (verbose stack-trace loop) can't exhaust client memory. Excess
    # bytes are dropped from the FRONT (FIFO) so the most-recent error
    # context is what callers see via ``get_stderr()``.
    STDERR_MAX_BYTES: int = 10 * 1024 * 1024

    def __init__(self, options: RpcClientOptions | None = None) -> None:
        self._options = options or RpcClientOptions()
        self._proc: asyncio.subprocess.Process | None = None
        self._stdout_reader_task: asyncio.Task[None] | None = None
        self._stderr_reader_task: asyncio.Task[None] | None = None
        self._stderr_buffer: bytearray = bytearray()
        self._event_listeners: list[Callable[[dict[str, Any]], None]] = []
        # Pi parity: requestId numeric monotonic counter, see ``rpc-client.ts:55``.
        self._next_id = itertools.count(1)
        self._pending_requests: dict[
            str, asyncio.Future[RpcSuccessResponse | RpcErrorResponse]
        ] = {}

    # === Lifecycle =============================================================

    async def start(self) -> None:
        """Pi parity: ``rpc-client.ts:60-83`` (``start``)."""

        if self._proc is not None:
            raise RuntimeError("RpcClient already started")

        argv = self._build_argv()
        env = self._build_env()

        self._proc = await asyncio.create_subprocess_exec(
            *argv,
            cwd=self._options.cwd,
            env=env,
            stdin=asyncio.subprocess.PIPE,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )

        proc_stdout = self._proc.stdout
        proc_stderr = self._proc.stderr
        if proc_stdout is None or proc_stderr is None:
            raise RuntimeError("Subprocess pipes are not connected")

        self._stdout_reader_task = asyncio.create_task(
            attach_jsonl_line_reader(proc_stdout, self._handle_stdout_line)
        )
        self._stderr_reader_task = asyncio.create_task(
            self._drain_stderr(proc_stderr)
        )

        # Pi parity: 100ms startup grace. If the child exits within
        # ``STARTUP_GRACE_MS`` we treat it as a launch failure.
        try:
            await asyncio.wait_for(
                self._proc.wait(),
                timeout=self.STARTUP_GRACE_MS / 1000.0,
            )
            # If wait returned before timeout, the process exited early.
            stderr_snapshot = self.get_stderr()
            raise RuntimeError(
                "RPC server exited prematurely with code "
                f"{self._proc.returncode}. Stderr: {stderr_snapshot}"
            )
        except TimeoutError:
            # Expected — the server is still running past the grace window.
            return

    async def stop(self) -> None:
        """Pi parity: ``rpc-client.ts:88-122`` (``stop``).

        SIGTERM → wait 1 s → SIGKILL. ``pending_requests`` are cleared so
        callers awaiting :meth:`send` see ``CancelledError`` propagate.
        """

        proc = self._proc
        if proc is None:
            return

        # W4 M3 — surface a meaningful exception to in-flight awaiters
        # (Pi parity: ``rpc-client.ts`` rejects pending promises with a
        # named error). Previously we called ``future.cancel()`` which
        # only delivered ``CancelledError`` with no command context.
        stop_error = RpcClientError("rpc", "RPC server stopped")
        for future in self._pending_requests.values():
            if not future.done():
                future.set_exception(stop_error)
        self._pending_requests.clear()

        with contextlib.suppress(ProcessLookupError):
            proc.terminate()
        try:
            await asyncio.wait_for(
                proc.wait(),
                timeout=self.SHUTDOWN_SIGTERM_TIMEOUT_MS / 1000.0,
            )
        except TimeoutError:
            with contextlib.suppress(ProcessLookupError):
                proc.kill()
            # W4 m9 — bound the final reap so a stuck child can't block
            # ``stop()`` forever. 5s is enough for a normal exit and
            # leaves the failure path observable via stderr capture.
            with contextlib.suppress(TimeoutError):
                await asyncio.wait_for(proc.wait(), timeout=5.0)

        for task in (self._stdout_reader_task, self._stderr_reader_task):
            if task is None:
                continue
            task.cancel()
            with contextlib.suppress(asyncio.CancelledError, Exception):  # noqa: BLE001
                await task

        self._proc = None
        self._stdout_reader_task = None
        self._stderr_reader_task = None

    # === Event subscription ====================================================

    def on_event(
        self, listener: Callable[[dict[str, Any]], None]
    ) -> Callable[[], None]:
        """Subscribe to streaming events. Returns an unsubscribe callable."""

        self._event_listeners.append(listener)

        def _unsubscribe() -> None:
            with contextlib.suppress(ValueError):
                self._event_listeners.remove(listener)

        return _unsubscribe

    def get_stderr(self) -> str:
        """Return captured stderr (Pi parity ``getStderr``)."""

        return self._stderr_buffer.decode("utf-8", errors="replace")

    # === Command surface (28 methods, Pi parity) ===============================

    async def prompt(
        self,
        message: str,
        images: list[dict[str, Any]] | None = None,
    ) -> None:
        await self._send({"type": "prompt", "message": message, "images": images})

    async def steer(
        self,
        message: str,
        images: list[dict[str, Any]] | None = None,
    ) -> None:
        await self._send({"type": "steer", "message": message, "images": images})

    async def follow_up(
        self,
        message: str,
        images: list[dict[str, Any]] | None = None,
    ) -> None:
        await self._send(
            {"type": "follow_up", "message": message, "images": images}
        )

    async def abort(self) -> None:
        await self._send({"type": "abort"})

    async def new_session(
        self, parent_session: str | None = None
    ) -> dict[str, Any]:
        response = await self._send(
            {"type": "new_session", "parentSession": parent_session}
        )
        return self._unwrap(response)

    async def get_state(self) -> RpcSessionState:
        response = await self._send({"type": "get_state"})
        data = self._unwrap(response)
        return RpcSessionState.from_json(data)

    async def set_model(self, provider: str, model_id: str) -> dict[str, Any]:
        response = await self._send(
            {"type": "set_model", "provider": provider, "modelId": model_id}
        )
        return self._unwrap(response)

    async def cycle_model(self) -> dict[str, Any] | None:
        response = await self._send({"type": "cycle_model"})
        return self._unwrap(response)

    async def get_available_models(self) -> list[dict[str, Any]]:
        response = await self._send({"type": "get_available_models"})
        data = self._unwrap(response)
        return list(data.get("models", []))

    async def set_thinking_level(self, level: str) -> None:
        await self._send({"type": "set_thinking_level", "level": level})

    async def cycle_thinking_level(self) -> dict[str, Any] | None:
        response = await self._send({"type": "cycle_thinking_level"})
        return self._unwrap(response)

    async def set_steering_mode(self, mode: str) -> None:
        await self._send({"type": "set_steering_mode", "mode": mode})

    async def set_follow_up_mode(self, mode: str) -> None:
        await self._send({"type": "set_follow_up_mode", "mode": mode})

    async def compact(
        self, custom_instructions: str | None = None
    ) -> dict[str, Any]:
        response = await self._send(
            {"type": "compact", "customInstructions": custom_instructions}
        )
        return self._unwrap(response)

    async def set_auto_compaction(self, enabled: bool) -> None:
        await self._send({"type": "set_auto_compaction", "enabled": enabled})

    async def set_auto_retry(self, enabled: bool) -> None:
        await self._send({"type": "set_auto_retry", "enabled": enabled})

    async def abort_retry(self) -> None:
        await self._send({"type": "abort_retry"})

    async def bash(self, command: str) -> dict[str, Any]:
        response = await self._send({"type": "bash", "command": command})
        return self._unwrap(response)

    async def abort_bash(self) -> None:
        await self._send({"type": "abort_bash"})

    async def get_session_stats(self) -> dict[str, Any]:
        response = await self._send({"type": "get_session_stats"})
        return self._unwrap(response)

    async def export_html(
        self, output_path: str | None = None
    ) -> dict[str, Any]:
        response = await self._send(
            {"type": "export_html", "outputPath": output_path}
        )
        return self._unwrap(response)

    async def switch_session(self, session_path: str) -> dict[str, Any]:
        response = await self._send(
            {"type": "switch_session", "sessionPath": session_path}
        )
        return self._unwrap(response)

    async def fork(self, entry_id: str) -> dict[str, Any]:
        response = await self._send({"type": "fork", "entryId": entry_id})
        return self._unwrap(response)

    async def clone(self) -> dict[str, Any]:
        response = await self._send({"type": "clone"})
        return self._unwrap(response)

    async def get_fork_messages(self) -> list[dict[str, Any]]:
        response = await self._send({"type": "get_fork_messages"})
        data = self._unwrap(response)
        return list(data.get("messages", []))

    async def get_last_assistant_text(self) -> str | None:
        response = await self._send({"type": "get_last_assistant_text"})
        data = self._unwrap(response)
        return data.get("text") if isinstance(data, dict) else None

    async def set_session_name(self, name: str) -> None:
        await self._send({"type": "set_session_name", "name": name})

    async def get_messages(self) -> list[dict[str, Any]]:
        response = await self._send({"type": "get_messages"})
        data = self._unwrap(response)
        return list(data.get("messages", []))

    async def get_commands(self) -> list[RpcSlashCommand]:
        response = await self._send({"type": "get_commands"})
        data = self._unwrap(response)
        result: list[RpcSlashCommand] = []
        for entry in data.get("commands", []):
            if not isinstance(entry, dict):
                continue
            result.append(
                RpcSlashCommand(
                    name=entry.get("name", ""),
                    source=entry.get("source", "extension"),
                    description=entry.get("description"),
                    source_info=entry.get("sourceInfo"),
                )
            )
        return result

    # === Utility helpers (Pi parity) ==========================================

    async def wait_for_idle(
        self, timeout_ms: int | None = None
    ) -> None:
        """Pi parity: ``rpc-client.ts:waitForIdle`` (60 s default).

        Resolves when an ``agent_end`` event arrives. Raises
        :class:`asyncio.TimeoutError` on timeout.
        """

        timeout_s = (timeout_ms or self.DEFAULT_WAIT_FOR_IDLE_MS) / 1000.0
        idle = asyncio.get_running_loop().create_future()

        def _listener(event: dict[str, Any]) -> None:
            if event.get("type") == "agent_end" and not idle.done():
                idle.set_result(None)

        unsubscribe = self.on_event(_listener)
        try:
            await asyncio.wait_for(idle, timeout=timeout_s)
        finally:
            unsubscribe()

    async def collect_events(
        self, timeout_ms: int | None = None
    ) -> list[dict[str, Any]]:
        """Pi parity: ``rpc-client.ts:collectEvents``."""

        timeout_s = (timeout_ms or self.DEFAULT_WAIT_FOR_IDLE_MS) / 1000.0
        collected: list[dict[str, Any]] = []
        done = asyncio.get_running_loop().create_future()

        def _listener(event: dict[str, Any]) -> None:
            collected.append(event)
            if event.get("type") == "agent_end" and not done.done():
                done.set_result(None)

        unsubscribe = self.on_event(_listener)
        try:
            await asyncio.wait_for(done, timeout=timeout_s)
        finally:
            unsubscribe()
        return collected

    async def prompt_and_wait(
        self,
        message: str,
        images: list[dict[str, Any]] | None = None,
        timeout_ms: int | None = None,
    ) -> list[dict[str, Any]]:
        """Pi parity: ``rpc-client.ts:promptAndWait``."""

        # Wire the listener BEFORE sending so we don't miss the
        # ``agent_end`` that fires synchronously in fast-stub scenarios.
        timeout_s = (timeout_ms or self.DEFAULT_WAIT_FOR_IDLE_MS) / 1000.0
        collected: list[dict[str, Any]] = []
        done = asyncio.get_running_loop().create_future()

        def _listener(event: dict[str, Any]) -> None:
            collected.append(event)
            if event.get("type") == "agent_end" and not done.done():
                done.set_result(None)

        unsubscribe = self.on_event(_listener)
        try:
            await self.prompt(message, images)
            await asyncio.wait_for(done, timeout=timeout_s)
        finally:
            unsubscribe()
        return collected

    # === Internals ============================================================

    def _build_argv(self) -> list[str]:
        """Pi parity: ``rpc-client.ts:62-72`` argv construction.

        Default: ``python -m aelix --mode rpc``. ``cli_path`` overrides the
        default invocation (e.g. for a custom shim or a one-off stub).
        """

        opts = self._options
        cli_path = opts.cli_path
        if cli_path is not None:
            argv: list[str] = [sys.executable, cli_path, "--mode", "rpc"]
        else:
            argv = [sys.executable, "-m", "aelix", "--mode", "rpc"]
        if opts.provider:
            argv.extend(["--provider", opts.provider])
        if opts.model:
            argv.extend(["--model", opts.model])
        argv.extend(opts.args)
        return argv

    def _build_env(self) -> dict[str, str]:
        env = dict(os.environ)
        env.update(self._options.env)
        return env

    async def _drain_stderr(self, stream: asyncio.StreamReader) -> None:
        """Continuously drain the child's stderr into the capture buffer.

        W4 M4 — buffer is capped at :attr:`STDERR_MAX_BYTES` (10 MB).
        Excess bytes are evicted from the FRONT (FIFO) so the most-recent
        diagnostics survive for ``get_stderr()`` callers.
        """

        while True:
            chunk = await stream.read(4096)
            if not chunk:
                return
            self._stderr_buffer.extend(chunk)
            if len(self._stderr_buffer) > self.STDERR_MAX_BYTES:
                overflow = len(self._stderr_buffer) - self.STDERR_MAX_BYTES
                del self._stderr_buffer[:overflow]

    def _handle_stdout_line(self, line: str) -> None:
        """Pi parity: ``rpc-client.ts:handleLine`` — response vs. event split."""

        if not line.strip():
            return
        try:
            payload = json.loads(line)
        except (json.JSONDecodeError, ValueError):
            # Pi swallows non-JSON lines silently.
            return
        if not isinstance(payload, dict):
            return
        if payload.get("type") == "response":
            request_id = payload.get("id")
            if isinstance(request_id, str) and request_id in self._pending_requests:
                try:
                    response = parse_rpc_response(payload)
                except ValueError:
                    return
                future = self._pending_requests.pop(request_id)
                if not future.done():
                    future.set_result(response)
                return
            # W4 m8 — response arrived AFTER the originating request was
            # timed-out + popped. Log to stderr before falling through to
            # event listeners so operators can correlate the drift.
            if isinstance(request_id, str):
                print(
                    f"[rpc-client] stale response id={request_id!r} "
                    f"command={payload.get('command')!r} (request already "
                    "completed/timed out)",
                    file=sys.stderr,
                    flush=True,
                )
            # Response without a tracked id — surface to event listeners
            # so callers can see protocol drift.
        for listener in list(self._event_listeners):
            # Listener errors are isolated (Pi parity — TS try/catch would
            # have prevented one listener from breaking the others).
            with contextlib.suppress(Exception):  # noqa: BLE001
                listener(payload)

    async def _send(
        self, command: dict[str, Any]
    ) -> RpcSuccessResponse | RpcErrorResponse:
        """Send a command and await the correlated response.

        Pi parity: ``rpc-client.ts:323-343``. Drops ``None`` values from
        the payload so the wire shape matches Pi's TS omits-undefined behavior.
        """

        if self._proc is None or self._proc.stdin is None:
            raise RuntimeError("RpcClient not started")

        request_id = f"req_{next(self._next_id)}"
        payload: dict[str, Any] = {"id": request_id}
        for key, value in command.items():
            if value is None:
                continue
            payload[key] = value

        future: asyncio.Future[
            RpcSuccessResponse | RpcErrorResponse
        ] = asyncio.get_running_loop().create_future()
        self._pending_requests[request_id] = future

        line = serialize_json_line(payload).encode("utf-8")
        self._proc.stdin.write(line)
        try:
            await self._proc.stdin.drain()
        except (BrokenPipeError, ConnectionResetError) as exc:
            self._pending_requests.pop(request_id, None)
            raise RuntimeError(f"RPC server closed stdin: {exc}") from exc

        try:
            response = await asyncio.wait_for(
                future, timeout=self.DEFAULT_SEND_TIMEOUT_MS / 1000.0
            )
        except TimeoutError:
            self._pending_requests.pop(request_id, None)
            stderr_snapshot = self.get_stderr()
            raise TimeoutError(
                f"Timeout waiting for response to {command.get('type')!r}. "
                f"Stderr: {stderr_snapshot}"
            ) from None
        return response

    def _unwrap(
        self, response: RpcSuccessResponse | RpcErrorResponse
    ) -> Any:
        """Pi parity: ``rpc-client.ts:getData`` — raise on error, return data otherwise."""

        if isinstance(response, RpcErrorResponse):
            raise RpcClientError(response.command, response.error)
        return response.data


# Some platforms (Windows) lack SIGTERM equivalents; expose for symmetry
# with Pi's ``rpc-client.ts:108`` so callers can verify the constant.
_SIGTERM = getattr(_signal, "SIGTERM", None)


__all__ = [
    "RpcClient",
    "RpcClientError",
    "RpcClientOptions",
]
