"""Golden-vector tests for ``short_hash`` (pi ``shortHash`` parity).

Expected outputs were generated by running pi's exact JavaScript
``shortHash`` under Node and cross-checked against the Python port; see
pi ``packages/ai/src/utils/hash.ts`` @ 927e98068cda. These vectors are
load-bearing: any drift breaks cross-turn reasoning/function-call
pairing for the OpenAI Responses adapter.
"""

from __future__ import annotations

import pytest
from aelix_ai.providers._short_hash import short_hash

# (input, expected) — verified byte-for-byte against Node.
_GOLDEN = [
    ("", "k4n83c7h0j2b"),
    ("a", "m8735310ae7sx"),
    ("hello", "1h6qa0qrowduu"),
    ("The quick brown fox", "na9l2t124bi96"),
    ("call_abc123", "sb0y391xa16ki"),
    ("x" * 100, "xxkuev1u7d0x5"),
    ("café", "1bgmwb2kxwh47"),  # multibyte (combining-free) BMP
    ("🦊", "1ak1gwxd3lrje"),  # non-BMP -> UTF-16 surrogate pair
    ("session-id-0123456789", "1175s4dp64agx"),
]


@pytest.mark.parametrize(("text", "expected"), _GOLDEN)
def test_short_hash_golden_vectors(text: str, expected: str) -> None:
    assert short_hash(text) == expected


def test_short_hash_is_deterministic() -> None:
    assert short_hash("repeatable") == short_hash("repeatable")


def test_short_hash_distinguishes_similar_inputs() -> None:
    assert short_hash("call_1") != short_hash("call_2")


def test_short_hash_output_is_base36_lowercase() -> None:
    out = short_hash("The quick brown fox")
    assert out
    assert all(c in "0123456789abcdefghijklmnopqrstuvwxyz" for c in out)


def test_short_hash_non_bmp_uses_utf16_code_units() -> None:
    # A non-BMP code point must hash as its UTF-16 surrogate pair, so it
    # differs from an empty string and is stable.
    assert short_hash("🦊") == "1ak1gwxd3lrje"
    assert short_hash("🦊") != short_hash("")
